# **E_COMMERCE DATA ANALYTICS PROJECT**

## Online Retail Dataset Analysis

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import kagglehub
path=kagglehub.dataset_download('vijayuv/onlineretail')

Using Colab cache for faster access to the 'onlineretail' dataset.


#🎯 Project Tasks

#PART A: Initial Data Exploration

Task 1: Load the dataset and display basic information about its structure.

In [ ]:
data = pd.read_csv('/kaggle/input/onlineretail/OnlineRetail.csv',encoding='ISO-8859-1')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


Task 2: Show the first 15 and last 15 records.

In [ ]:
data.head(15) #First 15 records.

InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1     536365     71053                  WHITE METAL LANTERN         6   
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5     536365     22752         SET 7 BABUSHKA NESTING BOXES         2   
6     536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6   
7     536366     22633               HAND WARMER UNION JACK         6   
8     536366     22632            HAND WARMER RED POLKA DOT         6   
9     536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32   
10    536367     22745           POPPY'S PLAYHOUSE BEDROOM          6   
11    536367     22748            POPPY'S PLAYHOUSE KITCHEN         6   
12    536367     22749    FELTCRAFT PRINCESS CHARLOTTE DOLL         8   
13    536367     22310              IVORY KNITTED MUG COSY          6   
14    536367     84969   BOX OF 6 ASSORTED COLOUR TEASPOONS         6   

       InvoiceDate  UnitPrice  CustomerID         Country  
0   12/1/2010 8:26       2.55     17850.0  United Kingdom  
1   12/1/2010 8:26       3.39     17850.0  United Kingdom  
2   12/1/2010 8:26       2.75     17850.0  United Kingdom  
3   12/1/2010 8:26       3.39     17850.0  United Kingdom  
4   12/1/2010 8:26       3.39     17850.0  United Kingdom  
5   12/1/2010 8:26       7.65     17850.0  United Kingdom  
6   12/1/2010 8:26       4.25     17850.0  United Kingdom  
7   12/1/2010 8:28       1.85     17850.0  United Kingdom  
8   12/1/2010 8:28       1.85     17850.0  United Kingdom  
9   12/1/2010 8:34       1.69     13047.0  United Kingdom  
10  12/1/2010 8:34       2.10     13047.0  United Kingdom  
11  12/1/2010 8:34       2.10     13047.0  United Kingdom  
12  12/1/2010 8:34       3.75     13047.0  United Kingdom  
13  12/1/2010 8:34       1.65     13047.0  United Kingdom  
14  12/1/2010 8:34       4.25     13047.0  United Kingdom

In [ ]:
data.tail(15) #Last 15 records.

InvoiceNo StockCode                      Description  Quantity  \
541894    581587     22631         CIRCUS PARADE LUNCH BOX         12   
541895    581587     22556   PLASTERS IN TIN CIRCUS PARADE         12   
541896    581587     22555        PLASTERS IN TIN STRONGMAN        12   
541897    581587     22728        ALARM CLOCK BAKELIKE PINK         4   
541898    581587     22727        ALARM CLOCK BAKELIKE RED          4   
541899    581587     22726       ALARM CLOCK BAKELIKE GREEN         4   
541900    581587     22730       ALARM CLOCK BAKELIKE IVORY         4   
541901    581587     22367  CHILDRENS APRON SPACEBOY DESIGN         8   
541902    581587     22629              SPACEBOY LUNCH BOX         12   
541903    581587     23256      CHILDRENS CUTLERY SPACEBOY          4   
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID Country  
541894  12/9/2011 12:50       1.95     12680.0  France  
541895  12/9/2011 12:50       1.65     12680.0  France  
541896  12/9/2011 12:50       1.65     12680.0  France  
541897  12/9/2011 12:50       3.75     12680.0  France  
541898  12/9/2011 12:50       3.75     12680.0  France  
541899  12/9/2011 12:50       3.75     12680.0  France  
541900  12/9/2011 12:50       3.75     12680.0  France  
541901  12/9/2011 12:50       1.95     12680.0  France  
541902  12/9/2011 12:50       1.95     12680.0  France  
541903  12/9/2011 12:50       4.15     12680.0  France  
541904  12/9/2011 12:50       0.85     12680.0  France  
541905  12/9/2011 12:50       2.10     12680.0  France  
541906  12/9/2011 12:50       4.15     12680.0  France  
541907  12/9/2011 12:50       4.15     12680.0  France  
541908  12/9/2011 12:50       4.95     12680.0  France

Task 3: Display a random sample of 20 transactions.

In [ ]:
data.sample(20)

InvoiceNo StockCode                          Description  Quantity  \
441014    574559     22467                    GUMBALL COAT RACK         3   
435709    574076     22718                   CARD CAT AND TREE          1   
328499    565780     21154            RED RETROSPOT OVEN GLOVE         20   
157437    550205     20676                   RED RETROSPOT BOWL         1   
160859    550470     22981                   PANTRY APPLE CORER         1   
87992     543740     84836          ZINC METAL HEART DECORATION        12   
334119    566230     20914  SET/5 RED RETROSPOT LID GLASS BOWLS        12   
471063    576618    84569D       PACK 6 HEART/ICE-CREAM PATCHES         1   
145614    548894     22678        FRENCH BLUE METAL DOOR SIGN 3         1   
42549     540005     21034         REX CASH+CARRY JUMBO SHOPPER         1   
52659     540813     22662          LUNCH BAG DOLLY GIRL DESIGN         3   
336879    566408     23298                       SPOTTY BUNTING         5   
236017    557671     22776          SWEETHEART CAKESTAND 3 TIER         1   
304027    563557     84879        ASSORTED COLOUR BIRD ORNAMENT        16   
492457    578120     21791   VINTAGE HEADS AND TAILS CARD GAME         12   
1657      536544     22744       MAKE YOUR OWN MONSOON CARD KIT         1   
13652     537434     22659              LUNCH BOX I LOVE LONDON         3   
367556    568897     23399        HOME SWEET HOME HANGING HEART        12   
53371     540832     20677                   PINK POLKADOT BOWL        12   
143282    548670     22728            ALARM CLOCK BAKELIKE PINK         2   

             InvoiceDate  UnitPrice  CustomerID         Country  
441014   11/4/2011 15:50       2.55     14056.0  United Kingdom  
435709   11/2/2011 15:38       0.83         NaN  United Kingdom  
328499    9/6/2011 15:30       1.25     13130.0  United Kingdom  
157437   4/15/2011 10:37       2.46         NaN  United Kingdom  
160859   4/18/2011 13:49       2.92         NaN  United Kingdom  
87992    2/11/2011 13:36       1.25     15311.0  United Kingdom  
334119   9/11/2011 10:57       2.95     15159.0  United Kingdom  
471063  11/15/2011 17:00       2.46         NaN  United Kingdom  
145614    4/4/2011 16:01       2.46         NaN  United Kingdom  
42549     1/4/2011 10:38       0.95     17315.0  United Kingdom  
52659    1/11/2011 12:41       1.65     14669.0  United Kingdom  
336879   9/12/2011 13:43       4.95     16984.0  United Kingdom  
236017   6/22/2011 10:11       9.95     13849.0  United Kingdom  
304027   8/17/2011 13:33       1.69     15786.0  United Kingdom  
492457  11/23/2011 10:21       1.25     14493.0  United Kingdom  
1657     12/1/2010 14:32       5.91         NaN  United Kingdom  
13652    12/6/2010 16:57       4.21         NaN  United Kingdom  
367556   9/29/2011 13:17       0.85     13886.0  United Kingdom  
53371    1/11/2011 14:42       1.63         NaN  United Kingdom  
143282    4/1/2011 15:37       3.75     15356.0  United Kingdom

Task 4: Find out how many rows and columns are in the dataset.

In [ ]:
data.shape

(541909, 8)

Task 5: List all column names.

In [ ]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Task 6: Check the data type of each column.

In [ ]:
data.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

Task 7: Get a statistical summary of all numerical columns.

In [ ]:
data.describe()

Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

#PART B: Data Quality Assessment
Task 8: Identify which columns have missing values and how many.

In [ ]:
data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Task 9: Find out how many transactions have missing CustomerID.

In [ ]:
data['CustomerID'].isna().sum()

np.int64(135080)

Task 10: Check if there are any duplicate rows in the dataset.

In [ ]:
data.duplicated().sum()

np.int64(5268)

Task 11: Identify transactions where Quantity is less than or equal to zero.

In [ ]:
data[data['Quantity'] <= 0]

InvoiceNo StockCode                       Description  Quantity  \
141      C536379         D                          Discount        -1   
154      C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1   
235      C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12   
236      C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24   
237      C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24   
...          ...       ...                               ...       ...   
540449   C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11   
541541   C581499         M                            Manual        -1   
541715   C581568     21258        VICTORIAN SEWING BOX LARGE        -5   
541716   C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1   
541717   C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5   

            InvoiceDate  UnitPrice  CustomerID         Country  
141      12/1/2010 9:41      27.50     14527.0  United Kingdom  
154      12/1/2010 9:49       4.65     15311.0  United Kingdom  
235     12/1/2010 10:24       1.65     17548.0  United Kingdom  
236     12/1/2010 10:24       0.29     17548.0  United Kingdom  
237     12/1/2010 10:24       0.29     17548.0  United Kingdom  
...                 ...        ...         ...             ...  
540449   12/9/2011 9:57       0.83     14397.0  United Kingdom  
541541  12/9/2011 10:28     224.69     15498.0  United Kingdom  
541715  12/9/2011 11:57      10.95     15311.0  United Kingdom  
541716  12/9/2011 11:58       1.25     17315.0  United Kingdom  
541717  12/9/2011 11:58       1.25     17315.0  United Kingdom  

[10624 rows x 8 columns]

Task 12: Find transactions where UnitPrice is zero or negative.

In [ ]:
data[data['UnitPrice'] <= 0]

InvoiceNo StockCode                   Description  Quantity  \
622       536414     22139                           NaN        56   
1970      536545     21134                           NaN         1   
1971      536546     22145                           NaN         1   
1972      536547     37509                           NaN         1   
1987      536549    85226A                           NaN         1   
...          ...       ...                           ...       ...   
536981    581234     72817                           NaN        27   
538504    581406    46000M  POLYESTER FILLER PAD 45x45cm       240   
538505    581406    46000S  POLYESTER FILLER PAD 40x40cm       300   
538554    581408     85175                           NaN        20   
538919    581422     23169                       smashed      -235   

            InvoiceDate  UnitPrice  CustomerID         Country  
622     12/1/2010 11:52        0.0         NaN  United Kingdom  
1970    12/1/2010 14:32        0.0         NaN  United Kingdom  
1971    12/1/2010 14:33        0.0         NaN  United Kingdom  
1972    12/1/2010 14:33        0.0         NaN  United Kingdom  
1987    12/1/2010 14:34        0.0         NaN  United Kingdom  
...                 ...        ...         ...             ...  
536981  12/8/2011 10:33        0.0         NaN  United Kingdom  
538504  12/8/2011 13:58        0.0         NaN  United Kingdom  
538505  12/8/2011 13:58        0.0         NaN  United Kingdom  
538554  12/8/2011 14:06        0.0         NaN  United Kingdom  
538919  12/8/2011 15:24        0.0         NaN  United Kingdom  

[2517 rows x 8 columns]

Task 13: Identify how many invoice numbers start with the letter 'C'.

In [ ]:
data['InvoiceNo'].str.startswith('C').sum()

np.int64(9288)

Task 14: Check if the Description column has any leading or trailing spaces.

In [ ]:
data['Description'] = data['Description'].str.strip()

In [ ]:
data['Description']

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...                 
541904            PACK OF 20 SPACEBOY NAPKINS
541905            CHILDREN'S APRON DOLLY GIRL
541906           CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908           BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 541909, dtype: object

##PART C: Data Cleaning
Task 15: Remove all rows where CustomerID is missing.

In [ ]:
data.head(3)

InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                 WHITE METAL LANTERN         6   
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom

In [ ]:
data.dropna(subset=['CustomerID'])

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[406829 rows x 8 columns]

Task 16: For missing product descriptions, fill them with "Unknown Product".

In [ ]:
data['Description'].fillna('Unknown Product',inplace=True)

In [ ]:
data[data['Description'] == 'Unknown Product']

InvoiceNo StockCode      Description  Quantity      InvoiceDate  \
622       536414     22139  Unknown Product        56  12/1/2010 11:52   
1970      536545     21134  Unknown Product         1  12/1/2010 14:32   
1971      536546     22145  Unknown Product         1  12/1/2010 14:33   
1972      536547     37509  Unknown Product         1  12/1/2010 14:33   
1987      536549    85226A  Unknown Product         1  12/1/2010 14:34   
...          ...       ...              ...       ...              ...   
535322    581199     84581  Unknown Product        -2  12/7/2011 18:26   
535326    581203     23406  Unknown Product        15  12/7/2011 18:31   
535332    581209     21620  Unknown Product         6  12/7/2011 18:35   
536981    581234     72817  Unknown Product        27  12/8/2011 10:33   
538554    581408     85175  Unknown Product        20  12/8/2011 14:06   

        UnitPrice  CustomerID         Country  
622           0.0         NaN  United Kingdom  
1970          0.0         NaN  United Kingdom  
1971          0.0         NaN  United Kingdom  
1972          0.0         NaN  United Kingdom  
1987          0.0         NaN  United Kingdom  
...           ...         ...             ...  
535322        0.0         NaN  United Kingdom  
535326        0.0         NaN  United Kingdom  
535332        0.0         NaN  United Kingdom  
536981        0.0         NaN  United Kingdom  
538554        0.0         NaN  United Kingdom  

[1454 rows x 8 columns]

Task 17: Remove all duplicate transactions.

In [ ]:
data.drop_duplicates(inplace = True)

In [ ]:
data

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[536641 rows x 8 columns]

Task 18: Remove transactions where Quantity is less than or equal to zero.

In [ ]:
trans = data[data['Quantity'] <= 0].index

In [ ]:
data1 = data.drop(trans)

In [ ]:
data

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[536641 rows x 8 columns]

Task 19: Remove transactions where UnitPrice is less than or equal to zero.

In [ ]:
trans1=data[data['UnitPrice'] <= 0].index

In [ ]:
data2 = data.drop(trans1)

In [ ]:
data

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[536641 rows x 8 columns]

Task 20: Remove all cancelled transactions (invoices starting with 'C').

In [ ]:
data1 = data['InvoiceNo'].str.startswith('C').index

In [ ]:
data3 = data.drop(data1)

In [ ]:
data

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[536641 rows x 8 columns]

Task 21: Change the column name "Description" to "ProductName".

In [ ]:
new_col = {'Description':'ProductName'}

In [ ]:
data.rename(columns = new_col, inplace = True)

In [ ]:
data.head(3)

InvoiceNo StockCode                         ProductName  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                 WHITE METAL LANTERN         6   
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom

Task 22: Ensure the InvoiceDate column is in proper date-time format.

In [ ]:
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    536641 non-null  object        
 1   StockCode    536641 non-null  object        
 2   ProductName  536641 non-null  object        
 3   Quantity     536641 non-null  int64         
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64       
 6   CustomerID   401604 non-null  float64       
 7   Country      536641 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 53.0+ MB


Task 23: Convert CustomerID to integer type.

In [ ]:
data['CustomerID'] = data['CustomerID'].fillna(0).astype(int)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    536641 non-null  object        
 1   StockCode    536641 non-null  object        
 2   ProductName  536641 non-null  object        
 3   Quantity     536641 non-null  int64         
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64       
 6   CustomerID   536641 non-null  int64         
 7   Country      536641 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 53.0+ MB


Task 24: Reset the index after all cleaning operations.

In [ ]:
data = data.reset_index(drop=True)

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55       17850  United Kingdom  
1      2010-12-01 08:26:00       3.39       17850  United Kingdom  
2      2010-12-01 08:26:00       2.75       17850  United Kingdom  
3      2010-12-01 08:26:00       3.39       17850  United Kingdom  
4      2010-12-01 08:26:00       3.39       17850  United Kingdom  
...                    ...        ...         ...             ...  
536636 2011-12-09 12:50:00       0.85       12680          France  
536637 2011-12-09 12:50:00       2.10       12680          France  
536638 2011-12-09 12:50:00       4.15       12680          France  
536639 2011-12-09 12:50:00       4.15       12680          France  
536640 2011-12-09 12:50:00       4.95       12680          France  

[536641 rows x 8 columns]

#PART D: Feature Creation

Task 25: Create a new column called "TotalPrice" that represents the total value of each transaction.

In [ ]:
data['Total_Price'] = data['Quantity']*data['UnitPrice']

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  Total_Price  
0      2010-12-01 08:26:00       2.55       17850  United Kingdom        15.30  
1      2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34  
2      2010-12-01 08:26:00       2.75       17850  United Kingdom        22.00  
3      2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34  
4      2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34  
...                    ...        ...         ...             ...          ...  
536636 2011-12-09 12:50:00       0.85       12680          France        10.20  
536637 2011-12-09 12:50:00       2.10       12680          France        12.60  
536638 2011-12-09 12:50:00       4.15       12680          France        16.60  
536639 2011-12-09 12:50:00       4.15       12680          France        16.60  
536640 2011-12-09 12:50:00       4.95       12680          France        14.85  

[536641 rows x 9 columns]

Task 26: Extract the year from InvoiceDate and store it in a new column "Year".

In [ ]:
data['Year'] = data['InvoiceDate'].dt.year

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  
0             15.30  2010  
1             20.34  2010  
2             22.00  2010  
3             20.34  2010  
4             20.34  2010  
...             ...   ...  
536636        10.20  2011  
536637        12.60  2011  
536638        16.60  2011  
536639        16.60  2011  
536640        14.85  2011  

[536641 rows x 10 columns]

Task 27: Extract the month from InvoiceDate and store it in a new column "Month".

In [ ]:
data['Month'] = data['InvoiceDate'].dt.month

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  Month  
0             15.30  2010     12  
1             20.34  2010     12  
2             22.00  2010     12  
3             20.34  2010     12  
4             20.34  2010     12  
...             ...   ...    ...  
536636        10.20  2011     12  
536637        12.60  2011     12  
536638        16.60  2011     12  
536639        16.60  2011     12  
536640        14.85  2011     12  

[536641 rows x 11 columns]

Task 28: Extract the day from InvoiceDate and store it in a new column "Day".

In [ ]:
data['Day'] = data['InvoiceDate'].dt.day

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  Month  Day  
0             15.30  2010     12    1  
1             20.34  2010     12    1  
2             22.00  2010     12    1  
3             20.34  2010     12    1  
4             20.34  2010     12    1  
...             ...   ...    ...  ...  
536636        10.20  2011     12    9  
536637        12.60  2011     12    9  
536638        16.60  2011     12    9  
536639        16.60  2011     12    9  
536640        14.85  2011     12    9  

[536641 rows x 12 columns]

Task 29: Extract the hour from InvoiceDate and store it in a new column "Hour".

In [ ]:
data['Hour'] = data['InvoiceDate'].dt.hour

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  Month  Day  Hour  
0             15.30  2010     12    1     8  
1             20.34  2010     12    1     8  
2             22.00  2010     12    1     8  
3             20.34  2010     12    1     8  
4             20.34  2010     12    1     8  
...             ...   ...    ...  ...   ...  
536636        10.20  2011     12    9    12  
536637        12.60  2011     12    9    12  
536638        16.60  2011     12    9    12  
536639        16.60  2011     12    9    12  
536640        14.85  2011     12    9    12  

[536641 rows x 13 columns]

Task 30: Create a column "DayOfWeek" showing which day of the week the transaction occurred.

In [ ]:
data['DayOfWeek'] = data['InvoiceDate'].dt.day_name()

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  Month  Day  Hour  DayOfWeek  
0             15.30  2010     12    1     8  Wednesday  
1             20.34  2010     12    1     8  Wednesday  
2             22.00  2010     12    1     8  Wednesday  
3             20.34  2010     12    1     8  Wednesday  
4             20.34  2010     12    1     8  Wednesday  
...             ...   ...    ...  ...   ...        ...  
536636        10.20  2011     12    9    12     Friday  
536637        12.60  2011     12    9    12     Friday  
536638        16.60  2011     12    9    12     Friday  
536639        16.60  2011     12    9    12     Friday  
536640        14.85  2011     12    9    12     Friday  

[536641 rows x 14 columns]

Task 31: Create a column "Quarter" showing which quarter (Q1, Q2, Q3, Q4) the transaction belongs to.

In [ ]:
data['Quarter'] = 'Q' + data['InvoiceDate'].dt.quarter.astype(str)

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
2      2010-12-01 08:26:00       2.75       17850  United Kingdom   
3      2010-12-01 08:26:00       3.39       17850  United Kingdom   
4      2010-12-01 08:26:00       3.39       17850  United Kingdom   
...                    ...        ...         ...             ...   
536636 2011-12-09 12:50:00       0.85       12680          France   
536637 2011-12-09 12:50:00       2.10       12680          France   
536638 2011-12-09 12:50:00       4.15       12680          France   
536639 2011-12-09 12:50:00       4.15       12680          France   
536640 2011-12-09 12:50:00       4.95       12680          France   

        Total_Price  Year  Month  Day  Hour  DayOfWeek Quarter  
0             15.30  2010     12    1     8  Wednesday      Q4  
1             20.34  2010     12    1     8  Wednesday      Q4  
2             22.00  2010     12    1     8  Wednesday      Q4  
3             20.34  2010     12    1     8  Wednesday      Q4  
4             20.34  2010     12    1     8  Wednesday      Q4  
...             ...   ...    ...  ...   ...        ...     ...  
536636        10.20  2011     12    9    12     Friday      Q4  
536637        12.60  2011     12    9    12     Friday      Q4  
536638        16.60  2011     12    9    12     Friday      Q4  
536639        16.60  2011     12    9    12     Friday      Q4  
536640        14.85  2011     12    9    12     Friday      Q4  

[536641 rows x 15 columns]

Task 32: Create a column "RevenueCategory" with three levels:

"Low" for transactions under £10,

"Medium" for transactions between £10 and £100,

"High" for transactions above £100.

In [ ]:
data['Revenue_Category'] = pd.cut(
    data['Total_Price'],
    bins=[-float('inf'), 10, 100, float('inf')],
    labels=['Low', 'Medium', 'High'],
    right=False
)

In [ ]:
data['Revenue_Category'].value_counts()

Revenue_Category
Low       278898
Medium    244175
High       13568
Name: count, dtype: int64

In [ ]:
data.head(6)

InvoiceNo StockCode                          ProductName  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2   

          InvoiceDate  UnitPrice  CustomerID         Country  Total_Price  \
0 2010-12-01 08:26:00       2.55       17850  United Kingdom        15.30   
1 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
2 2010-12-01 08:26:00       2.75       17850  United Kingdom        22.00   
3 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
4 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
5 2010-12-01 08:26:00       7.65       17850  United Kingdom        15.30   

   Year  Month  Day  Hour  DayOfWeek Quarter Revenue_Category  
0  2010     12    1     8  Wednesday      Q4           Medium  
1  2010     12    1     8  Wednesday      Q4           Medium  
2  2010     12    1     8  Wednesday      Q4           Medium  
3  2010     12    1     8  Wednesday      Q4           Medium  
4  2010     12    1     8  Wednesday      Q4           Medium  
5  2010     12    1     8  Wednesday      Q4           Medium

Task 33: Create a column "OrderSize" with three levels:

"Small" for Quantity less than 5,

"Medium" for Quantity between 5 and 20,

"Large" for Quantity greater than 20.

In [ ]:
data['OrderSize'] = pd.cut(
    data['Quantity'],
    bins=[-float('inf'), 5, 20, float('inf')],
    labels=['Small', 'Medium', 'Large'],
    right=False
)


In [ ]:
data.head(8)

InvoiceNo StockCode                          ProductName  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2   
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6   
7    536366     22633               HAND WARMER UNION JACK         6   

          InvoiceDate  UnitPrice  CustomerID         Country  Total_Price  \
0 2010-12-01 08:26:00       2.55       17850  United Kingdom        15.30   
1 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
2 2010-12-01 08:26:00       2.75       17850  United Kingdom        22.00   
3 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
4 2010-12-01 08:26:00       3.39       17850  United Kingdom        20.34   
5 2010-12-01 08:26:00       7.65       17850  United Kingdom        15.30   
6 2010-12-01 08:26:00       4.25       17850  United Kingdom        25.50   
7 2010-12-01 08:28:00       1.85       17850  United Kingdom        11.10   

   Year  Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0  2010     12    1     8  Wednesday      Q4           Medium    Medium  
1  2010     12    1     8  Wednesday      Q4           Medium    Medium  
2  2010     12    1     8  Wednesday      Q4           Medium    Medium  
3  2010     12    1     8  Wednesday      Q4           Medium    Medium  
4  2010     12    1     8  Wednesday      Q4           Medium    Medium  
5  2010     12    1     8  Wednesday      Q4           Medium     Small  
6  2010     12    1     8  Wednesday      Q4           Medium    Medium  
7  2010     12    1     8  Wednesday      Q4           Medium    Medium

Task 34: Create a column that shows the length of each product name.

In [ ]:
data['ProductName'].size

536641

#PART E: Text Data Processing
Task 35: Convert all product names to uppercase.

In [ ]:
data['ProductName'].str.upper()

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...                 
536636            PACK OF 20 SPACEBOY NAPKINS
536637            CHILDREN'S APRON DOLLY GIRL
536638           CHILDRENS CUTLERY DOLLY GIRL
536639        CHILDRENS CUTLERY CIRCUS PARADE
536640           BAKING SET 9 PIECE RETROSPOT
Name: ProductName, Length: 536641, dtype: object

Task 36: Remove any extra spaces from the Country column.

In [ ]:
data['Country'].str.strip()

0         United Kingdom
1         United Kingdom
2         United Kingdom
3         United Kingdom
4         United Kingdom
               ...      
536636            France
536637            France
536638            France
536639            France
536640            France
Name: Country, Length: 536641, dtype: object

Task 37: Find all products that contain the word "BAG" in their name.

In [ ]:
data_bag = data[data['ProductName'].str.contains('BAG')]


In [ ]:

data_bag

InvoiceNo StockCode                      ProductName  Quantity  \
38        536370     22661  CHARLOTTE BAG DOLLY GIRL DESIGN        20   
86        536378     22386          JUMBO BAG PINK POLKADOT        10   
87        536378    85099C   JUMBO  BAG BAROQUE BLACK WHITE        10   
88        536378     21033  JUMBO BAG CHARLIE AND LOLA TOYS        10   
89        536378     20723         STRAWBERRY CHARLOTTE BAG        10   
...          ...       ...                              ...       ...   
536565    581579     23343      JUMBO BAG VINTAGE CHRISTMAS        30   
536566    581579     23344         JUMBO BAG 50'S CHRISTMAS        20   
536567    581579     23581           JUMBO BAG PAISLEY PARK        40   
536594    581581     23681      LUNCH BAG RED VINTAGE DOILY        10   
536597    581583     20725          LUNCH BAG RED RETROSPOT        40   

               InvoiceDate  UnitPrice  CustomerID         Country  \
38     2010-12-01 08:45:00       0.85       12583          France   
86     2010-12-01 09:37:00       1.95       14688  United Kingdom   
87     2010-12-01 09:37:00       1.95       14688  United Kingdom   
88     2010-12-01 09:37:00       2.95       14688  United Kingdom   
89     2010-12-01 09:37:00       0.85       14688  United Kingdom   
...                    ...        ...         ...             ...   
536565 2011-12-09 12:19:00       1.79       17581  United Kingdom   
536566 2011-12-09 12:19:00       1.79       17581  United Kingdom   
536567 2011-12-09 12:19:00       1.79       17581  United Kingdom   
536594 2011-12-09 12:20:00       1.65       17581  United Kingdom   
536597 2011-12-09 12:23:00       1.45       13777  United Kingdom   

        Total_Price  Year  Month  Day  Hour  DayOfWeek Quarter  \
38             17.0  2010     12    1     8  Wednesday      Q4   
86             19.5  2010     12    1     9  Wednesday      Q4   
87             19.5  2010     12    1     9  Wednesday      Q4   
88             29.5  2010     12    1     9  Wednesday      Q4   
89              8.5  2010     12    1     9  Wednesday      Q4   
...             ...   ...    ...  ...   ...        ...     ...   
536565         53.7  2011     12    9    12     Friday      Q4   
536566         35.8  2011     12    9    12     Friday      Q4   
536567         71.6  2011     12    9    12     Friday      Q4   
536594         16.5  2011     12    9    12     Friday      Q4   
536597         58.0  2011     12    9    12     Friday      Q4   

       Revenue_Category OrderSize  
38               Medium     Large  
86               Medium    Medium  
87               Medium    Medium  
88               Medium    Medium  
89                  Low    Medium  
...                 ...       ...  
536565           Medium     Large  
536566           Medium     Large  
536567           Medium     Large  
536594           Medium    Medium  
536597           Medium     Large  

[52668 rows x 17 columns]

Task 38: Find all products whose names start with "WHITE".

In [ ]:
data[data['ProductName'].str.startswith('WHITE')]

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
49        536373    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
50        536373     71053                  WHITE METAL LANTERN         6   
66        536375    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
...          ...       ...                                  ...       ...   
536018    581497     21673  WHITE SPOT BLUE CERAMIC DRAWER KNOB         1   
536250    581498     71053         WHITE MOROCCAN METAL LANTERN         1   
536318    581502     23210     WHITE ROCKING HORSE HAND PAINTED        12   
536385    581538     21673  WHITE SPOT BLUE CERAMIC DRAWER KNOB         1   
536444    581567     21479         WHITE SKULL HOT WATER BOTTLE         4   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom   
49     2010-12-01 09:02:00       2.55       17850  United Kingdom   
50     2010-12-01 09:02:00       3.39       17850  United Kingdom   
66     2010-12-01 09:32:00       2.55       17850  United Kingdom   
...                    ...        ...         ...             ...   
536018 2011-12-09 10:23:00       3.29           0  United Kingdom   
536250 2011-12-09 10:26:00       8.29           0  United Kingdom   
536318 2011-12-09 10:51:00       1.25       15910  United Kingdom   
536385 2011-12-09 11:34:00       1.45       14446  United Kingdom   
536444 2011-12-09 11:56:00       4.25       16626  United Kingdom   

        Total_Price  Year  Month  Day  Hour  DayOfWeek Quarter  \
0             15.30  2010     12    1     8  Wednesday      Q4   
1             20.34  2010     12    1     8  Wednesday      Q4   
49            15.30  2010     12    1     9  Wednesday      Q4   
50            20.34  2010     12    1     9  Wednesday      Q4   
66            15.30  2010     12    1     9  Wednesday      Q4   
...             ...   ...    ...  ...   ...        ...     ...   
536018         3.29  2011     12    9    10     Friday      Q4   
536250         8.29  2011     12    9    10     Friday      Q4   
536318        15.00  2011     12    9    10     Friday      Q4   
536385         1.45  2011     12    9    11     Friday      Q4   
536444        17.00  2011     12    9    11     Friday      Q4   

       Revenue_Category OrderSize  
0                Medium    Medium  
1                Medium    Medium  
49               Medium    Medium  
50               Medium    Medium  
66               Medium    Medium  
...                 ...       ...  
536018              Low     Small  
536250              Low     Small  
536318           Medium    Medium  
536385              Low     Small  
536444           Medium     Small  

[7021 rows x 17 columns]

Task 39: Find all products whose names end with "HOLDER".

In [ ]:
data[data['ProductName'].str.endswith('HOLDER')]

InvoiceNo StockCode                         ProductName  Quantity  \
0         536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
6         536365     21730   GLASS STAR FROSTED T-LIGHT HOLDER         6   
49        536373    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
64        536373     21730   GLASS STAR FROSTED T-LIGHT HOLDER         6   
66        536375    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
...          ...       ...                                 ...       ...   
536464    581571     21313          GLASS HEART T-LIGHT HOLDER         1   
536473    581571     85053          FRENCH ENAMEL CANDLEHOLDER         2   
536557    581579     22197                      POPCORN HOLDER        24   
536604    581585     22460      EMBOSSED GLASS TEALIGHT HOLDER        12   
536608    581585     84945  MULTI COLOUR SILVER T-LIGHT HOLDER        24   

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom   
6      2010-12-01 08:26:00       4.25       17850  United Kingdom   
49     2010-12-01 09:02:00       2.55       17850  United Kingdom   
64     2010-12-01 09:02:00       4.25       17850  United Kingdom   
66     2010-12-01 09:32:00       2.55       17850  United Kingdom   
...                    ...        ...         ...             ...   
536464 2011-12-09 12:00:00       0.85       15311  United Kingdom   
536473 2011-12-09 12:00:00       2.10       15311  United Kingdom   
536557 2011-12-09 12:19:00       0.85       17581  United Kingdom   
536604 2011-12-09 12:31:00       1.25       15804  United Kingdom   
536608 2011-12-09 12:31:00       0.85       15804  United Kingdom   

        Total_Price  Year  Month  Day  Hour  DayOfWeek Quarter  \
0             15.30  2010     12    1     8  Wednesday      Q4   
6             25.50  2010     12    1     8  Wednesday      Q4   
49            15.30  2010     12    1     9  Wednesday      Q4   
64            25.50  2010     12    1     9  Wednesday      Q4   
66            15.30  2010     12    1     9  Wednesday      Q4   
...             ...   ...    ...  ...   ...        ...     ...   
536464         0.85  2011     12    9    12     Friday      Q4   
536473         4.20  2011     12    9    12     Friday      Q4   
536557        20.40  2011     12    9    12     Friday      Q4   
536604        15.00  2011     12    9    12     Friday      Q4   
536608        20.40  2011     12    9    12     Friday      Q4   

       Revenue_Category OrderSize  
0                Medium    Medium  
6                Medium    Medium  
49               Medium    Medium  
64               Medium    Medium  
66               Medium    Medium  
...                 ...       ...  
536464              Low     Small  
536473              Low     Small  
536557           Medium     Large  
536604           Medium    Medium  
536608           Medium     Large  

[14010 rows x 17 columns]

Task 40: Replace "United Kingdom" with "UK" in the Country column.

In [ ]:
data['Country'] = data['Country'].str.replace('United Kingdom', 'UK')

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536636 2011-12-09 12:50:00       0.85       12680  France        10.20  2011   
536637 2011-12-09 12:50:00       2.10       12680  France        12.60  2011   
536638 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0          12    1     8  Wednesday      Q4           Medium    Medium  
1          12    1     8  Wednesday      Q4           Medium    Medium  
2          12    1     8  Wednesday      Q4           Medium    Medium  
3          12    1     8  Wednesday      Q4           Medium    Medium  
4          12    1     8  Wednesday      Q4           Medium    Medium  
...       ...  ...   ...        ...     ...              ...       ...  
536636     12    9    12     Friday      Q4           Medium    Medium  
536637     12    9    12     Friday      Q4           Medium    Medium  
536638     12    9    12     Friday      Q4           Medium     Small  
536639     12    9    12     Friday      Q4           Medium     Small  
536640     12    9    12     Friday      Q4           Medium     Small  

[536641 rows x 17 columns]

Task 41: Replace "EIRE" with "Ireland" in the Country column.

In [ ]:
data['Country'] = data['Country'].str.replace('EIRE', 'Ireland')

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536636 2011-12-09 12:50:00       0.85       12680  France        10.20  2011   
536637 2011-12-09 12:50:00       2.10       12680  France        12.60  2011   
536638 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0          12    1     8  Wednesday      Q4           Medium    Medium  
1          12    1     8  Wednesday      Q4           Medium    Medium  
2          12    1     8  Wednesday      Q4           Medium    Medium  
3          12    1     8  Wednesday      Q4           Medium    Medium  
4          12    1     8  Wednesday      Q4           Medium    Medium  
...       ...  ...   ...        ...     ...              ...       ...  
536636     12    9    12     Friday      Q4           Medium    Medium  
536637     12    9    12     Friday      Q4           Medium    Medium  
536638     12    9    12     Friday      Q4           Medium     Small  
536639     12    9    12     Friday      Q4           Medium     Small  
536640     12    9    12     Friday      Q4           Medium     Small  

[536641 rows x 17 columns]

#PART F: Data Selection and Filtering

Task 42: Select only the columns: InvoiceNo, ProductName, Quantity, UnitPrice, Country.

In [ ]:
dt = data[['InvoiceNo', 'ProductName', 'Quantity', 'UnitPrice', 'Country']]

In [ ]:
dt

InvoiceNo                          ProductName  Quantity  UnitPrice  \
0         536365   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55   
1         536365                  WHITE METAL LANTERN         6       3.39   
2         536365       CREAM CUPID HEARTS COAT HANGER         8       2.75   
3         536365  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39   
4         536365       RED WOOLLY HOTTIE WHITE HEART.         6       3.39   
...          ...                                  ...       ...        ...   
536636    581587          PACK OF 20 SPACEBOY NAPKINS        12       0.85   
536637    581587          CHILDREN'S APRON DOLLY GIRL         6       2.10   
536638    581587         CHILDRENS CUTLERY DOLLY GIRL         4       4.15   
536639    581587      CHILDRENS CUTLERY CIRCUS PARADE         4       4.15   
536640    581587         BAKING SET 9 PIECE RETROSPOT         3       4.95   

       Country  
0           UK  
1           UK  
2           UK  
3           UK  
4           UK  
...        ...  
536636  France  
536637  France  
536638  France  
536639  France  
536640  France  

[536641 rows x 5 columns]

Task 43: Display transactions from Germany only.

In [ ]:
data[data['Country'] == 'Germany']

InvoiceNo StockCode                          ProductName  Quantity  \
1084      536527     22809              SET OF 6 T-LIGHTS SANTA         6   
1085      536527     84347  ROTATING SILVER ANGELS T-LIGHT HLDR         6   
1086      536527     84945   MULTI COLOUR SILVER T-LIGHT HOLDER        12   
1087      536527     22242        5 HOOK HANGER MAGIC TOADSTOOL        12   
1088      536527     22244           3 HOOK HANGER MAGIC GARDEN        12   
...          ...       ...                                  ...       ...   
536533    581578     22993         SET OF 4 PANTRY JELLY MOULDS        12   
536534    581578     22907     PACK OF 20 NAPKINS PANTRY DESIGN        12   
536535    581578     22908        PACK OF 20 NAPKINS RED APPLES        12   
536536    581578     23215     JINGLE BELL HEART ANTIQUE SILVER        12   
536537    581578     22736           RIBBON REEL MAKING SNOWMEN        10   

               InvoiceDate  UnitPrice  CustomerID  Country  Total_Price  Year  \
1084   2010-12-01 13:04:00       2.95       12662  Germany        17.70  2010   
1085   2010-12-01 13:04:00       2.55       12662  Germany        15.30  2010   
1086   2010-12-01 13:04:00       0.85       12662  Germany        10.20  2010   
1087   2010-12-01 13:04:00       1.65       12662  Germany        19.80  2010   
1088   2010-12-01 13:04:00       1.95       12662  Germany        23.40  2010   
...                    ...        ...         ...      ...          ...   ...   
536533 2011-12-09 12:16:00       1.25       12713  Germany        15.00  2011   
536534 2011-12-09 12:16:00       0.85       12713  Germany        10.20  2011   
536535 2011-12-09 12:16:00       0.85       12713  Germany        10.20  2011   
536536 2011-12-09 12:16:00       2.08       12713  Germany        24.96  2011   
536537 2011-12-09 12:16:00       1.65       12713  Germany        16.50  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
1084       12    1    13  Wednesday      Q4           Medium    Medium  
1085       12    1    13  Wednesday      Q4           Medium    Medium  
1086       12    1    13  Wednesday      Q4           Medium    Medium  
1087       12    1    13  Wednesday      Q4           Medium    Medium  
1088       12    1    13  Wednesday      Q4           Medium    Medium  
...       ...  ...   ...        ...     ...              ...       ...  
536533     12    9    12     Friday      Q4           Medium    Medium  
536534     12    9    12     Friday      Q4           Medium    Medium  
536535     12    9    12     Friday      Q4           Medium    Medium  
536536     12    9    12     Friday      Q4           Medium    Medium  
536537     12    9    12     Friday      Q4           Medium    Medium  

[9480 rows x 17 columns]

Task 44: Display transactions where Quantity is greater than 50.

In [ ]:
data[data['Quantity'] > 50]

InvoiceNo StockCode                         ProductName  Quantity  \
46        536371     22086      PAPER CHAIN KIT 50'S CHRISTMAS        80   
83        536376     21733    RED HANGING HEART T-LIGHT HOLDER        64   
96        536378     21212     PACK OF 72 RETROSPOT CAKE CASES       120   
102       536378    85071B  RED CHARLIE+LOLA PERSONAL DOORSIGN        96   
176       536386    85099C      JUMBO  BAG BAROQUE BLACK WHITE       100   
...          ...       ...                                 ...       ...   
536434    581566     23404          HOME SWEET HOME BLACKBOARD       144   
536435    581567     21417                   COCKLE SHELL DISH        84   
536443    581567     21326    AGED GLASS SILVER T-LIGHT HOLDER       144   
536478    581571     23167       SMALL CERAMIC TOP STORAGE JAR        96   
536599    581584     20832    RED FLOCK LOVE HEART PHOTO FRAME        72   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
46     2010-12-01 09:00:00       2.55       13748      UK       204.00  2010   
83     2010-12-01 09:32:00       2.55       15291      UK       163.20  2010   
96     2010-12-01 09:37:00       0.42       14688      UK        50.40  2010   
102    2010-12-01 09:37:00       0.38       14688      UK        36.48  2010   
176    2010-12-01 09:57:00       1.65       16029      UK       165.00  2010   
...                    ...        ...         ...     ...          ...   ...   
536434 2011-12-09 11:50:00       3.26       18102      UK       469.44  2011   
536435 2011-12-09 11:56:00       0.79       16626      UK        66.36  2011   
536443 2011-12-09 11:56:00       0.55       16626      UK        79.20  2011   
536478 2011-12-09 12:00:00       0.69       15311      UK        66.24  2011   
536599 2011-12-09 12:25:00       0.72       13777      UK        51.84  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
46         12    1     9  Wednesday      Q4             High     Large  
83         12    1     9  Wednesday      Q4             High     Large  
96         12    1     9  Wednesday      Q4           Medium     Large  
102        12    1     9  Wednesday      Q4           Medium     Large  
176        12    1     9  Wednesday      Q4             High     Large  
...       ...  ...   ...        ...     ...              ...       ...  
536434     12    9    11     Friday      Q4             High     Large  
536435     12    9    11     Friday      Q4           Medium     Large  
536443     12    9    11     Friday      Q4           Medium     Large  
536478     12    9    12     Friday      Q4           Medium     Large  
536599     12    9    12     Friday      Q4           Medium     Large  

[12312 rows x 17 columns]

Task 45: Display transactions where UnitPrice is between £5 and £10.

In [ ]:
data[(data['UnitPrice'] >= 5) & (data['UnitPrice'] <= 10)]

InvoiceNo StockCode                     ProductName  Quantity  \
5         536365     22752    SET 7 BABUSHKA NESTING BOXES         2   
16        536367     22622  BOX OF VINTAGE ALPHABET BLOCKS         2   
17        536367     21754        HOME BUILDING BLOCK WORD         3   
18        536367     21755        LOVE BUILDING BLOCK WORD         3   
19        536367     21777     RECIPE BOX WITH METAL HEART         4   
...          ...       ...                             ...       ...   
536587    581580     21351        CINAMMON & ORANGE WREATH         1   
536590    581580     79321                   CHILLI LIGHTS         2   
536610    581585     23356           LOVE HOT WATER BOTTLE         3   
536624    581586     21217   RED RETROSPOT ROUND CAKE TINS        24   
536625    581586     20685           DOORMAT RED RETROSPOT        10   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
5      2010-12-01 08:26:00       7.65       17850      UK        15.30  2010   
16     2010-12-01 08:34:00       9.95       13047      UK        19.90  2010   
17     2010-12-01 08:34:00       5.95       13047      UK        17.85  2010   
18     2010-12-01 08:34:00       5.95       13047      UK        17.85  2010   
19     2010-12-01 08:34:00       7.95       13047      UK        31.80  2010   
...                    ...        ...         ...     ...          ...   ...   
536587 2011-12-09 12:20:00       6.75       12748      UK         6.75  2011   
536590 2011-12-09 12:20:00       5.75       12748      UK        11.50  2011   
536610 2011-12-09 12:31:00       5.95       15804      UK        17.85  2011   
536624 2011-12-09 12:49:00       8.95       13113      UK       214.80  2011   
536625 2011-12-09 12:49:00       7.08       13113      UK        70.80  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
5          12    1     8  Wednesday      Q4           Medium     Small  
16         12    1     8  Wednesday      Q4           Medium     Small  
17         12    1     8  Wednesday      Q4           Medium     Small  
18         12    1     8  Wednesday      Q4           Medium     Small  
19         12    1     8  Wednesday      Q4           Medium     Small  
...       ...  ...   ...        ...     ...              ...       ...  
536587     12    9    12     Friday      Q4              Low     Small  
536590     12    9    12     Friday      Q4           Medium     Small  
536610     12    9    12     Friday      Q4           Medium     Small  
536624     12    9    12     Friday      Q4             High     Large  
536625     12    9    12     Friday      Q4           Medium    Medium  

[62616 rows x 17 columns]

Task 46: Display transactions from France with Quantity greater than 20.

In [ ]:
data[(data['Country'] == 'France') & (data['Quantity'] > 20)]

InvoiceNo StockCode                        ProductName  Quantity  \
26        536370     22728          ALARM CLOCK BAKELIKE PINK        24   
27        536370     22727           ALARM CLOCK BAKELIKE RED        24   
30        536370     21883                    STARS GIFT TAPE        24   
31        536370     10002         INFLATABLE POLITICAL GLOBE        48   
32        536370     21791  VINTAGE HEADS AND TAILS CARD GAME        24   
...          ...       ...                                ...       ...   
527726    581001     23084                 RABBIT NIGHT LIGHT        24   
527740    581001     22726         ALARM CLOCK BAKELIKE GREEN        24   
529562    581171     22966      GINGERBREAD MAN COOKIE CUTTER        24   
529573    581171     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS        48   
529580    581171     23084                 RABBIT NIGHT LIGHT        24   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
26     2010-12-01 08:45:00       3.75       12583  France        90.00  2010   
27     2010-12-01 08:45:00       3.75       12583  France        90.00  2010   
30     2010-12-01 08:45:00       0.65       12583  France        15.60  2010   
31     2010-12-01 08:45:00       0.85       12583  France        40.80  2010   
32     2010-12-01 08:45:00       1.25       12583  France        30.00  2010   
...                    ...        ...         ...     ...          ...   ...   
527726 2011-12-07 08:07:00       1.79       12583  France        42.96  2011   
527740 2011-12-07 08:07:00       3.75       12583  France        90.00  2011   
529562 2011-12-07 15:02:00       1.25       12615  France        30.00  2011   
529573 2011-12-07 15:02:00       0.29       12615  France        13.92  2011   
529580 2011-12-07 15:02:00       1.79       12615  France        42.96  2011   

        Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
26         12    1     8  Wednesday      Q4           Medium     Large  
27         12    1     8  Wednesday      Q4           Medium     Large  
30         12    1     8  Wednesday      Q4           Medium     Large  
31         12    1     8  Wednesday      Q4           Medium     Large  
32         12    1     8  Wednesday      Q4           Medium     Large  
...       ...  ...   ...        ...     ...              ...       ...  
527726     12    7     8  Wednesday      Q4           Medium     Large  
527740     12    7     8  Wednesday      Q4           Medium     Large  
529562     12    7    15  Wednesday      Q4           Medium     Large  
529573     12    7    15  Wednesday      Q4           Medium     Large  
529580     12    7    15  Wednesday      Q4           Medium     Large  

[1423 rows x 17 columns]

Task 47: Display transactions from December 2010.

In [ ]:
data['Month'] = data['InvoiceDate'].dt.month_name()

In [ ]:
data

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536636 2011-12-09 12:50:00       0.85       12680  France        10.20  2011   
536637 2011-12-09 12:50:00       2.10       12680  France        12.60  2011   
536638 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0       December    1     8  Wednesday      Q4           Medium    Medium  
1       December    1     8  Wednesday      Q4           Medium    Medium  
2       December    1     8  Wednesday      Q4           Medium    Medium  
3       December    1     8  Wednesday      Q4           Medium    Medium  
4       December    1     8  Wednesday      Q4           Medium    Medium  
...          ...  ...   ...        ...     ...              ...       ...  
536636  December    9    12     Friday      Q4           Medium    Medium  
536637  December    9    12     Friday      Q4           Medium    Medium  
536638  December    9    12     Friday      Q4           Medium     Small  
536639  December    9    12     Friday      Q4           Medium     Small  
536640  December    9    12     Friday      Q4           Medium     Small  

[536641 rows x 17 columns]

In [ ]:
data[(data['Month'] == 'December') & (data['Year'] == 2010)]

InvoiceNo StockCode                          ProductName  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1        536365     71053                  WHITE METAL LANTERN         6   
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...         ...       ...                                  ...       ...   
41976    539991     21618       4 WILDFLOWER BOTANICAL CANDLES         1   
41977    539991     72741                GRAND CHOCOLATECANDLE         4   
41978    539992     21470        FLOWER VINE RAFFIA FOOD COVER         1   
41979    539992     22258              FELT FARM ANIMAL RABBIT         1   
41980    539992     21155                RED RETROSPOT PEG BAG         1   

              InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0     2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1     2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2     2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3     2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4     2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                   ...        ...         ...     ...          ...   ...   
41976 2010-12-23 16:49:00       1.25           0      UK         1.25  2010   
41977 2010-12-23 16:49:00       1.45           0      UK         5.80  2010   
41978 2010-12-23 17:41:00       3.75           0      UK         3.75  2010   
41979 2010-12-23 17:41:00       1.25           0      UK         1.25  2010   
41980 2010-12-23 17:41:00       2.10           0      UK         2.10  2010   

          Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0      December    1     8  Wednesday      Q4           Medium    Medium  
1      December    1     8  Wednesday      Q4           Medium    Medium  
2      December    1     8  Wednesday      Q4           Medium    Medium  
3      December    1     8  Wednesday      Q4           Medium    Medium  
4      December    1     8  Wednesday      Q4           Medium    Medium  
...         ...  ...   ...        ...     ...              ...       ...  
41976  December   23    16   Thursday      Q4              Low     Small  
41977  December   23    16   Thursday      Q4              Low     Small  
41978  December   23    17   Thursday      Q4              Low     Small  
41979  December   23    17   Thursday      Q4              Low     Small  
41980  December   23    17   Thursday      Q4              Low     Small  

[41981 rows x 17 columns]

Task 48: Display transactions that occurred on weekends.

In [ ]:
weekend_df = data[data['InvoiceDate'].dt.weekday >= 5]

weekend_df

InvoiceNo StockCode                          ProductName  Quantity  \
7317      537037     22114    HOT WATER BOTTLE TEA AND SYMPATHY         8   
7318      537037     21485     RETROSPOT HEART HOT WATER BOTTLE         6   
7319      537037     22835      HOT WATER BOTTLE I AM SO POORLY         3   
7320      537037    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
7321      537037    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
...          ...       ...                                  ...       ...   
519093    580537     23266  SET OF 3 WOODEN STOCKING DECORATION         1   
519094    580537     23267        SET OF 4 SANTA PLACE SETTINGS         1   
519095    580537     23312          VINTAGE CHRISTMAS GIFT SACK         2   
519096    580537     23319          BOX OF 6 MINI 50'S CRACKERS         1   
519097    580537     23320         GIANT 50'S CHRISTMAS CRACKER         2   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
7317   2010-12-05 10:03:00       3.95       17243      UK        31.60  2010   
7318   2010-12-05 10:03:00       4.95       17243      UK        29.70  2010   
7319   2010-12-05 10:03:00       4.65       17243      UK        13.95  2010   
7320   2010-12-05 10:03:00       3.75       17243      UK        22.50  2010   
7321   2010-12-05 10:03:00       3.75       17243      UK        22.50  2010   
...                    ...        ...         ...     ...          ...   ...   
519093 2011-12-04 16:08:00       1.25           0      UK         1.25  2011   
519094 2011-12-04 16:08:00       1.25           0      UK         1.25  2011   
519095 2011-12-04 16:08:00       4.15           0      UK         8.30  2011   
519096 2011-12-04 16:08:00       2.49           0      UK         2.49  2011   
519097 2011-12-04 16:08:00       1.25           0      UK         2.50  2011   

           Month  Day  Hour DayOfWeek Quarter Revenue_Category OrderSize  
7317    December    5    10    Sunday      Q4           Medium    Medium  
7318    December    5    10    Sunday      Q4           Medium    Medium  
7319    December    5    10    Sunday      Q4           Medium     Small  
7320    December    5    10    Sunday      Q4           Medium    Medium  
7321    December    5    10    Sunday      Q4           Medium    Medium  
...          ...  ...   ...       ...     ...              ...       ...  
519093  December    4    16    Sunday      Q4              Low     Small  
519094  December    4    16    Sunday      Q4              Low     Small  
519095  December    4    16    Sunday      Q4              Low     Small  
519096  December    4    16    Sunday      Q4              Low     Small  
519097  December    4    16    Sunday      Q4              Low     Small  

[62806 rows x 17 columns]

Task 49: Display the top 10 transactions by TotalPrice.

In [ ]:
top10 = data.sort_values(by='Total_Price', ascending=False).head(10)
top10


InvoiceNo  StockCode                          ProductName  Quantity  \
535160    581483      23843          PAPER CRAFT , LITTLE BIRDIE     80995   
61006     541431      23166       MEDIUM CERAMIC TOP STORAGE JAR     74215   
220825    556444      22502       PICNIC BASKET WICKER 60 PIECES        60   
14757     537632  AMAZONFEE                           AMAZON FEE         1   
297645   A563185          B                      Adjust bad debt         1   
171873    551697       POST                              POSTAGE         1   
345627    567423      23243  SET OF TEA COFFEE SUGAR TINS PANTRY      1412   
52169     540815      21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114   
159101    550461      21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114   
418088    573003      23084                   RABBIT NIGHT LIGHT      2400   

               InvoiceDate  UnitPrice  CustomerID      Country  Total_Price  \
535160 2011-12-09 09:15:00       2.08       16446           UK    168469.60   
61006  2011-01-18 10:01:00       1.04       12346           UK     77183.60   
220825 2011-06-10 15:28:00     649.50       15098           UK     38970.00   
14757  2010-12-07 15:08:00   13541.33           0           UK     13541.33   
297645 2011-08-12 14:50:00   11062.06           0           UK     11062.06   
171873 2011-05-03 13:46:00    8142.75       16029           UK      8142.75   
345627 2011-09-20 11:05:00       5.06       17450           UK      7144.72   
52169  2011-01-11 12:55:00       2.10       15749           UK      6539.40   
159101 2011-04-18 13:20:00       2.10       15749           UK      6539.40   
418088 2011-10-27 12:11:00       2.08       14646  Netherlands      4992.00   

        Year      Month  Day  Hour DayOfWeek Quarter Revenue_Category  \
535160  2011   December    9     9    Friday      Q4             High   
61006   2011    January   18    10   Tuesday      Q1             High   
220825  2011       June   10    15    Friday      Q2             High   
14757   2010   December    7    15   Tuesday      Q4             High   
297645  2011     August   12    14    Friday      Q3             High   
171873  2011        May    3    13   Tuesday      Q2             High   
345627  2011  September   20    11   Tuesday      Q3             High   
52169   2011    January   11    12   Tuesday      Q1             High   
159101  2011      April   18    13    Monday      Q2             High   
418088  2011    October   27    12  Thursday      Q4             High   

       OrderSize  
535160     Large  
61006      Large  
220825     Large  
14757      Small  
297645     Small  
171873     Small  
345627     Large  
52169      Large  
159101     Large  
418088     Large

Task 50: Display the bottom 15 transactions by TotalPrice.

In [ ]:
bottom15 = data.sort_values(by='Total_Price', ascending=True).head(15)
bottom15


InvoiceNo  StockCode                     ProductName  Quantity  \
535161   C581484      23843     PAPER CRAFT , LITTLE BIRDIE    -80995   
61011    C541433      23166  MEDIUM CERAMIC TOP STORAGE JAR    -74215   
220826   C556445          M                          Manual        -1   
519497   C580605  AMAZONFEE                      AMAZON FEE        -1   
43193    C540117  AMAZONFEE                      AMAZON FEE        -1   
43194    C540118  AMAZONFEE                      AMAZON FEE        -1   
16087    C537651  AMAZONFEE                      AMAZON FEE        -1   
14756    C537630  AMAZONFEE                      AMAZON FEE        -1   
15972    C537644  AMAZONFEE                      AMAZON FEE        -1   
519496   C580604  AMAZONFEE                      AMAZON FEE        -1   
297646   A563186          B                 Adjust bad debt         1   
297647   A563187          B                 Adjust bad debt         1   
418855   C573079          M                          Manual        -2   
442657   C574902  AMAZONFEE                      AMAZON FEE        -1   
171769   C551685       POST                         POSTAGE        -1   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
535161 2011-12-09 09:27:00       2.08       16446      UK   -168469.60  2011   
61011  2011-01-18 10:17:00       1.04       12346      UK    -77183.60  2011   
220826 2011-06-10 15:31:00   38970.00       15098      UK    -38970.00  2011   
519497 2011-12-05 11:36:00   17836.46           0      UK    -17836.46  2011   
43193  2011-01-05 09:55:00   16888.02           0      UK    -16888.02  2011   
43194  2011-01-05 09:57:00   16453.71           0      UK    -16453.71  2011   
16087  2010-12-07 15:49:00   13541.33           0      UK    -13541.33  2010   
14756  2010-12-07 15:04:00   13541.33           0      UK    -13541.33  2010   
15972  2010-12-07 15:34:00   13474.79           0      UK    -13474.79  2010   
519496 2011-12-05 11:35:00   11586.50           0      UK    -11586.50  2011   
297646 2011-08-12 14:51:00  -11062.06           0      UK    -11062.06  2011   
297647 2011-08-12 14:52:00  -11062.06           0      UK    -11062.06  2011   
418855 2011-10-27 14:15:00    4161.06       12536  France     -8322.12  2011   
442657 2011-11-07 15:21:00    8286.22           0      UK     -8286.22  2011   
171769 2011-05-03 12:51:00    8142.75       16029      UK     -8142.75  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
535161  December    9     9     Friday      Q4              Low     Small  
61011    January   18    10    Tuesday      Q1              Low     Small  
220826      June   10    15     Friday      Q2              Low     Small  
519497  December    5    11     Monday      Q4              Low     Small  
43193    January    5     9  Wednesday      Q1              Low     Small  
43194    January    5     9  Wednesday      Q1              Low     Small  
16087   December    7    15    Tuesday      Q4              Low     Small  
14756   December    7    15    Tuesday      Q4              Low     Small  
15972   December    7    15    Tuesday      Q4              Low     Small  
519496  December    5    11     Monday      Q4              Low     Small  
297646    August   12    14     Friday      Q3              Low     Small  
297647    August   12    14     Friday      Q3              Low     Small  
418855   October   27    14   Thursday      Q4              Low     Small  
442657  November    7    15     Monday      Q4              Low     Small  
171769       May    3    12    Tuesday      Q2              Low     Small

Task 51: Find all transactions from either UK, Germany, or France.

In [ ]:
d1 = data[data['Country'].isin(['UK','Germany','France'])]

In [ ]:
d1

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536636 2011-12-09 12:50:00       0.85       12680  France        10.20  2011   
536637 2011-12-09 12:50:00       2.10       12680  France        12.60  2011   
536638 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0       December    1     8  Wednesday      Q4           Medium    Medium  
1       December    1     8  Wednesday      Q4           Medium    Medium  
2       December    1     8  Wednesday      Q4           Medium    Medium  
3       December    1     8  Wednesday      Q4           Medium    Medium  
4       December    1     8  Wednesday      Q4           Medium    Medium  
...          ...  ...   ...        ...     ...              ...       ...  
536636  December    9    12     Friday      Q4           Medium    Medium  
536637  December    9    12     Friday      Q4           Medium    Medium  
536638  December    9    12     Friday      Q4           Medium     Small  
536639  December    9    12     Friday      Q4           Medium     Small  
536640  December    9    12     Friday      Q4           Medium     Small  

[508321 rows x 17 columns]

Task 52: Find transactions where TotalPrice is above the 95th percentile.

In [ ]:
threshold = data['Total_Price'].quantile(0.95)

high_value_transactions = data[data['Total_Price'] > threshold]

high_value_transactions


InvoiceNo StockCode                         ProductName  Quantity  \
26        536370     22728           ALARM CLOCK BAKELIKE PINK        24   
27        536370     22727            ALARM CLOCK BAKELIKE RED        24   
34        536370     22326  ROUND SNACK BOXES SET OF4 WOODLAND        24   
40        536370     22900      SET 2 TEA TOWELS I LOVE LONDON        24   
46        536371     22086      PAPER CHAIN KIT 50'S CHRISTMAS        80   
...          ...       ...                                 ...       ...   
536567    581579     23581              JUMBO BAG PAISLEY PARK        40   
536598    581583     85038     6 CHOCOLATE LOVE HEART T-LIGHTS        36   
536600    581584     85038     6 CHOCOLATE LOVE HEART T-LIGHTS        48   
536624    581586     21217       RED RETROSPOT ROUND CAKE TINS        24   
536625    581586     20685               DOORMAT RED RETROSPOT        10   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
26     2010-12-01 08:45:00       3.75       12583  France         90.0  2010   
27     2010-12-01 08:45:00       3.75       12583  France         90.0  2010   
34     2010-12-01 08:45:00       2.95       12583  France         70.8  2010   
40     2010-12-01 08:45:00       2.95       12583  France         70.8  2010   
46     2010-12-01 09:00:00       2.55       13748      UK        204.0  2010   
...                    ...        ...         ...     ...          ...   ...   
536567 2011-12-09 12:19:00       1.79       17581      UK         71.6  2011   
536598 2011-12-09 12:23:00       1.85       13777      UK         66.6  2011   
536600 2011-12-09 12:25:00       1.85       13777      UK         88.8  2011   
536624 2011-12-09 12:49:00       8.95       13113      UK        214.8  2011   
536625 2011-12-09 12:49:00       7.08       13113      UK         70.8  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
26      December    1     8  Wednesday      Q4           Medium     Large  
27      December    1     8  Wednesday      Q4           Medium     Large  
34      December    1     8  Wednesday      Q4           Medium     Large  
40      December    1     8  Wednesday      Q4           Medium     Large  
46      December    1     9  Wednesday      Q4             High     Large  
...          ...  ...   ...        ...     ...              ...       ...  
536567  December    9    12     Friday      Q4           Medium     Large  
536598  December    9    12     Friday      Q4           Medium     Large  
536600  December    9    12     Friday      Q4           Medium     Large  
536624  December    9    12     Friday      Q4             High     Large  
536625  December    9    12     Friday      Q4           Medium    Medium  

[26621 rows x 17 columns]

#PART G: Sorting Operations

Task 53: Sort the entire dataset by InvoiceDate in ascending order.

In [ ]:
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])

df_sorted = data.sort_values(by='InvoiceDate', ascending=True)

df_sorted


InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536628    581587     22555            PLASTERS IN TIN STRONGMAN        12   
536627    581587     22556        PLASTERS IN TIN CIRCUS PARADE        12   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536632    581587     22730           ALARM CLOCK BAKELIKE IVORY         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536628 2011-12-09 12:50:00       1.65       12680  France        19.80  2011   
536627 2011-12-09 12:50:00       1.65       12680  France        19.80  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536632 2011-12-09 12:50:00       3.75       12680  France        15.00  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0       December    1     8  Wednesday      Q4           Medium    Medium  
1       December    1     8  Wednesday      Q4           Medium    Medium  
2       December    1     8  Wednesday      Q4           Medium    Medium  
3       December    1     8  Wednesday      Q4           Medium    Medium  
4       December    1     8  Wednesday      Q4           Medium    Medium  
...          ...  ...   ...        ...     ...              ...       ...  
536628  December    9    12     Friday      Q4           Medium    Medium  
536627  December    9    12     Friday      Q4           Medium    Medium  
536639  December    9    12     Friday      Q4           Medium     Small  
536632  December    9    12     Friday      Q4           Medium     Small  
536640  December    9    12     Friday      Q4           Medium     Small  

[536641 rows x 17 columns]

Task 54: Sort the dataset by TotalPrice in descending order.

In [ ]:
df_sorted = data.sort_values(by='Total_Price', ascending=True)

df_sorted


InvoiceNo  StockCode                     ProductName  Quantity  \
535161   C581484      23843     PAPER CRAFT , LITTLE BIRDIE    -80995   
61011    C541433      23166  MEDIUM CERAMIC TOP STORAGE JAR    -74215   
220826   C556445          M                          Manual        -1   
519497   C580605  AMAZONFEE                      AMAZON FEE        -1   
43193    C540117  AMAZONFEE                      AMAZON FEE        -1   
...          ...        ...                             ...       ...   
297645   A563185          B                 Adjust bad debt         1   
14757     537632  AMAZONFEE                      AMAZON FEE         1   
220825    556444      22502  PICNIC BASKET WICKER 60 PIECES        60   
61006     541431      23166  MEDIUM CERAMIC TOP STORAGE JAR     74215   
535160    581483      23843     PAPER CRAFT , LITTLE BIRDIE     80995   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
535161 2011-12-09 09:27:00       2.08       16446      UK   -168469.60  2011   
61011  2011-01-18 10:17:00       1.04       12346      UK    -77183.60  2011   
220826 2011-06-10 15:31:00   38970.00       15098      UK    -38970.00  2011   
519497 2011-12-05 11:36:00   17836.46           0      UK    -17836.46  2011   
43193  2011-01-05 09:55:00   16888.02           0      UK    -16888.02  2011   
...                    ...        ...         ...     ...          ...   ...   
297645 2011-08-12 14:50:00   11062.06           0      UK     11062.06  2011   
14757  2010-12-07 15:08:00   13541.33           0      UK     13541.33  2010   
220825 2011-06-10 15:28:00     649.50       15098      UK     38970.00  2011   
61006  2011-01-18 10:01:00       1.04       12346      UK     77183.60  2011   
535160 2011-12-09 09:15:00       2.08       16446      UK    168469.60  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
535161  December    9     9     Friday      Q4              Low     Small  
61011    January   18    10    Tuesday      Q1              Low     Small  
220826      June   10    15     Friday      Q2              Low     Small  
519497  December    5    11     Monday      Q4              Low     Small  
43193    January    5     9  Wednesday      Q1              Low     Small  
...          ...  ...   ...        ...     ...              ...       ...  
297645    August   12    14     Friday      Q3             High     Small  
14757   December    7    15    Tuesday      Q4             High     Small  
220825      June   10    15     Friday      Q2             High     Large  
61006    January   18    10    Tuesday      Q1             High     Large  
535160  December    9     9     Friday      Q4             High     Large  

[536641 rows x 17 columns]

Task 55: Sort by Country (ascending) and then by TotalPrice (descending).

In [ ]:
df_sorted = data.sort_values(
    by=['Country', 'Total_Price'],
    ascending=[True, False]
)

df_sorted


InvoiceNo StockCode                        ProductName  Quantity  \
463974    576394     23084                 RABBIT NIGHT LIGHT       960   
302523    563614     22940          FELTCRAFT CHRISTMAS FAIRY       336   
107022    545475     21217      RED RETROSPOT ROUND CAKE TINS       120   
302593    563614     23314       VINTAGE CHRISTMAS TABLECLOTH       100   
45030     540267     22720   SET OF 3 CAKE TINS PANTRY DESIGN       240   
...          ...       ...                                ...       ...   
320909    565303     22541              MINI JIGSAW LEAP FROG         1   
320910    565303     22540          MINI JIGSAW CIRCUS PARADE         1   
280554    561658    47348A      FUSCHIA VOILE POINTY SHOE DEC         1   
280605    561661     22396      MAGNETS PACK OF 4 RETRO PHOTO         1   
280580    561661    79063C  RETRO PILL BOX KEY CHAIN,THE KING         1   

               InvoiceDate  UnitPrice  CustomerID      Country  Total_Price  \
463974 2011-11-15 10:32:00       1.79       12415    Australia      1718.40   
302523 2011-08-18 08:51:00       3.75       12415    Australia      1260.00   
107022 2011-03-03 10:59:00       8.95       12415    Australia      1074.00   
302593 2011-08-18 08:51:00      10.39       12415    Australia      1039.00   
45030  2011-01-06 11:12:00       4.25       12415    Australia      1020.00   
...                    ...        ...         ...          ...          ...   
320909 2011-09-02 12:17:00       0.42           0  Unspecified         0.42   
320910 2011-09-02 12:17:00       0.42           0  Unspecified         0.42   
280554 2011-07-28 16:06:00       0.39       12743  Unspecified         0.39   
280605 2011-07-28 16:21:00       0.39       12743  Unspecified         0.39   
280580 2011-07-28 16:21:00       0.19       12743  Unspecified         0.19   

        Year      Month  Day  Hour DayOfWeek Quarter Revenue_Category  \
463974  2011   November   15    10   Tuesday      Q4             High   
302523  2011     August   18     8  Thursday      Q3             High   
107022  2011      March    3    10  Thursday      Q1             High   
302593  2011     August   18     8  Thursday      Q3             High   
45030   2011    January    6    11  Thursday      Q1             High   
...      ...        ...  ...   ...       ...     ...              ...   
320909  2011  September    2    12    Friday      Q3              Low   
320910  2011  September    2    12    Friday      Q3              Low   
280554  2011       July   28    16  Thursday      Q3              Low   
280605  2011       July   28    16  Thursday      Q3              Low   
280580  2011       July   28    16  Thursday      Q3              Low   

       OrderSize  
463974     Large  
302523     Large  
107022     Large  
302593     Large  
45030      Large  
...          ...  
320909     Small  
320910     Small  
280554     Small  
280605     Small  
280580     Small  

[536641 rows x 17 columns]

Task 56: Find the 20 highest-value transactions.

In [ ]:
top20 = data.sort_values(by='Total_Price', ascending=False).head(20)
top20

InvoiceNo  StockCode                          ProductName  Quantity  \
535160    581483      23843          PAPER CRAFT , LITTLE BIRDIE     80995   
61006     541431      23166       MEDIUM CERAMIC TOP STORAGE JAR     74215   
220825    556444      22502       PICNIC BASKET WICKER 60 PIECES        60   
14757     537632  AMAZONFEE                           AMAZON FEE         1   
297645   A563185          B                      Adjust bad debt         1   
171873    551697       POST                              POSTAGE         1   
345627    567423      23243  SET OF TEA COFFEE SUGAR TINS PANTRY      1412   
52169     540815      21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114   
159101    550461      21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114   
418088    573003      23084                   RABBIT NIGHT LIGHT      2400   
52167     540815     85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930   
463639    576365      22086       PAPER CHAIN KIT 50'S CHRISTMAS       688   
159097    550461     85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930   
52229     540818      48185                   DOORMAT FAIRY CAKE       670   
295392    562955        DOT                       DOTCOM POSTAGE         1   
242413    558526      23173                 REGENCY TEAPOT ROSES       540   
265857    560373          M                               Manual         1   
159099    550461      48185                   DOORMAT FAIRY CAKE       670   
288962    562439      84879        ASSORTED COLOUR BIRD ORNAMENT      2880   
418831    573077          M                               Manual         1   

               InvoiceDate  UnitPrice  CustomerID      Country  Total_Price  \
535160 2011-12-09 09:15:00       2.08       16446           UK    168469.60   
61006  2011-01-18 10:01:00       1.04       12346           UK     77183.60   
220825 2011-06-10 15:28:00     649.50       15098           UK     38970.00   
14757  2010-12-07 15:08:00   13541.33           0           UK     13541.33   
297645 2011-08-12 14:50:00   11062.06           0           UK     11062.06   
171873 2011-05-03 13:46:00    8142.75       16029           UK      8142.75   
345627 2011-09-20 11:05:00       5.06       17450           UK      7144.72   
52169  2011-01-11 12:55:00       2.10       15749           UK      6539.40   
159101 2011-04-18 13:20:00       2.10       15749           UK      6539.40   
418088 2011-10-27 12:11:00       2.08       14646  Netherlands      4992.00   
52167  2011-01-11 12:55:00       2.55       15749           UK      4921.50   
463639 2011-11-14 17:55:00       6.95           0           UK      4781.60   
159097 2011-04-18 13:20:00       2.40       15749           UK      4632.00   
52229  2011-01-11 12:57:00       6.75       15749           UK      4522.50   
295392 2011-08-11 10:14:00    4505.17           0           UK      4505.17   
242413 2011-06-30 11:01:00       8.15       17949           UK      4401.00   
265857 2011-07-18 12:30:00    4287.63           0           UK      4287.63   
159099 2011-04-18 13:20:00       6.35       15749           UK      4254.50   
288962 2011-08-04 18:06:00       1.45       12931           UK      4176.00   
418831 2011-10-27 14:13:00    4161.06       12536       France      4161.06   

        Year      Month  Day  Hour DayOfWeek Quarter Revenue_Category  \
535160  2011   December    9     9    Friday      Q4             High   
61006   2011    January   18    10   Tuesday      Q1             High   
220825  2011       June   10    15    Friday      Q2             High   
14757   2010   December    7    15   Tuesday      Q4             High   
297645  2011     August   12    14    Friday      Q3             High   
171873  2011        May    3    13   Tuesday      Q2             High   
345627  2011  September   20    11   Tuesday      Q3             High   
52169   2011    January   11    12   Tuesday      Q1             High   
159101  2011      April   18    13    Monday      Q

Task 57: Find the 20 lowest-value transactions (excluding returns).

In [ ]:
low20 = data.sort_values(by='Total_Price', ascending=True).head(20)

In [ ]:
low20

InvoiceNo  StockCode                     ProductName  Quantity  \
535161   C581484      23843     PAPER CRAFT , LITTLE BIRDIE    -80995   
61011    C541433      23166  MEDIUM CERAMIC TOP STORAGE JAR    -74215   
220826   C556445          M                          Manual        -1   
519497   C580605  AMAZONFEE                      AMAZON FEE        -1   
43193    C540117  AMAZONFEE                      AMAZON FEE        -1   
43194    C540118  AMAZONFEE                      AMAZON FEE        -1   
16087    C537651  AMAZONFEE                      AMAZON FEE        -1   
14756    C537630  AMAZONFEE                      AMAZON FEE        -1   
15972    C537644  AMAZONFEE                      AMAZON FEE        -1   
519496   C580604  AMAZONFEE                      AMAZON FEE        -1   
297646   A563186          B                 Adjust bad debt         1   
297647   A563187          B                 Adjust bad debt         1   
418855   C573079          M                          Manual        -2   
442657   C574902  AMAZONFEE                      AMAZON FEE        -1   
171769   C551685       POST                         POSTAGE        -1   
339969   C566899  AMAZONFEE                      AMAZON FEE        -1   
189762   C553355  AMAZONFEE                      AMAZON FEE        -1   
171882   C551699          M                          Manual        -1   
284881   C562086  AMAZONFEE                      AMAZON FEE        -1   
16088    C537652  AMAZONFEE                      AMAZON FEE        -1   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
535161 2011-12-09 09:27:00       2.08       16446      UK   -168469.60  2011   
61011  2011-01-18 10:17:00       1.04       12346      UK    -77183.60  2011   
220826 2011-06-10 15:31:00   38970.00       15098      UK    -38970.00  2011   
519497 2011-12-05 11:36:00   17836.46           0      UK    -17836.46  2011   
43193  2011-01-05 09:55:00   16888.02           0      UK    -16888.02  2011   
43194  2011-01-05 09:57:00   16453.71           0      UK    -16453.71  2011   
16087  2010-12-07 15:49:00   13541.33           0      UK    -13541.33  2010   
14756  2010-12-07 15:04:00   13541.33           0      UK    -13541.33  2010   
15972  2010-12-07 15:34:00   13474.79           0      UK    -13474.79  2010   
519496 2011-12-05 11:35:00   11586.50           0      UK    -11586.50  2011   
297646 2011-08-12 14:51:00  -11062.06           0      UK    -11062.06  2011   
297647 2011-08-12 14:52:00  -11062.06           0      UK    -11062.06  2011   
418855 2011-10-27 14:15:00    4161.06       12536  France     -8322.12  2011   
442657 2011-11-07 15:21:00    8286.22           0      UK     -8286.22  2011   
171769 2011-05-03 12:51:00    8142.75       16029      UK     -8142.75  2011   
339969 2011-09-15 13:53:00    7427.97           0      UK     -7427.97  2011   
189762 2011-05-16 13:58:00    7006.83           0      UK     -7006.83  2011   
171882 2011-05-03 14:12:00    6930.00       16029      UK     -6930.00  2011   
284881 2011-08-02 12:27:00    6721.37           0      UK     -6721.37  2011   
16088  2010-12-07 15:51:00    6706.71           0      UK     -6706.71  2010   

            Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
535161   December    9     9     Friday      Q4              Low     Small  
61011     January   18    10    Tuesday      Q1              Low     Small  
220826       June   10    15     Friday      Q2              Low     Small  
519497   December    5    11     Monday      Q4              Low     Small  
43193     January    5     9  Wednesday      Q1              Low     Small  
43194     January    5     9  Wednesday      Q1              Low     Small  
16087    December    7    15    Tuesday      Q4              Low     Small  
14756    December    7    15    Tuesday      Q4              Low     Small  
15972    December    7    15    Tuesday      Q4              Low     Small  
519496   December    5

#PART H: Aggregation and Summary Statistics

Task 58: Calculate the total revenue generated across all transactions.

In [ ]:
total_revenue = data['Total_Price'].sum()

In [ ]:
total_revenue

np.float64(9726006.953999998)

Task 59: Calculate the average transaction value.

In [ ]:
Avg_revenue = data['Total_Price'].mean()

In [ ]:
Avg_revenue

np.float64(18.123861117581395)

Task 60: Find the maximum and minimum transaction values.

In [ ]:
max_trans = data['Total_Price'].max()

In [ ]:
min_trans = data['Total_Price'].min()

In [ ]:
max_trans

168469.6

In [ ]:
min_trans

-168469.6

Task 61: Calculate the total number of unique customers.

In [ ]:
data['CustomerID'].nunique()

4373

Task 62: Calculate the total number of unique products sold.

In [ ]:
data['ProductName'].nunique()

4212

Task 63: Find out how many unique countries are represented in the data.

In [ ]:
data['Country'].nunique()

38

Task 64: Calculate the average number of items per transaction.

In [ ]:
data['Quantity'].mean()

np.float64(9.620029032444409)

Task 65: Find which product appears most frequently in transactions.

In [ ]:
data['ProductName'].value_counts().head(1)

ProductName
WHITE HANGING HEART T-LIGHT HOLDER    2357
Name: count, dtype: int64

#PART I: Country-wise Analysis

Task 66: Calculate total revenue for each country.

In [ ]:
country_revenue = data.groupby('Country')['Total_Price'].sum().sort_values(ascending=False)
country_revenue


Country
UK                      8167128.184
Netherlands              284661.540
Ireland                  262993.380
Germany                  221509.470
France                   197317.110
Australia                137009.770
Switzerland               56363.050
Spain                     54756.030
Belgium                   40910.960
Sweden                    36585.410
Japan                     35340.620
Norway                    35163.460
Portugal                  29302.970
Finland                   22326.740
Channel Islands           20076.390
Denmark                   18768.140
Italy                     16890.510
Cyprus                    12858.760
Austria                   10154.320
Hong Kong                  9908.240
Singapore                  9120.390
Israel                     7901.970
Poland                     7213.140
Unspecified                4740.940
Greece                     4710.520
Iceland                    4310.000
Canada                     3666.380
Malta                      2505.470
United Arab Emirates       1902.280
USA                        1730.920
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1291.750
Brazil                     1143.600
RSA                        1002.310
Czech Republic              707.720
Bahrain                     548.400
Saudi Arabia                131.170
Name: Total_Price, dtype: float64

Task 67: Find the top 10 countries by total revenue.

In [ ]:
country_revenue = data.groupby('Country')['Total_Price'].sum().sort_values(ascending=False).head(10)
country_revenue

Country
UK             8167128.184
Netherlands     284661.540
Ireland         262993.380
Germany         221509.470
France          197317.110
Australia       137009.770
Switzerland      56363.050
Spain            54756.030
Belgium          40910.960
Sweden           36585.410
Name: Total_Price, dtype: float64

Task 68: Calculate the number of transactions per country.

In [ ]:
data['Country'].value_counts()

Country
UK                      490300
Germany                   9480
France                    8541
Ireland                   8184
Spain                     2528
Netherlands               2371
Belgium                   2069
Switzerland               1994
Portugal                  1510
Australia                 1258
Norway                    1086
Italy                      803
Channel Islands            757
Finland                    695
Cyprus                     611
Sweden                     461
Unspecified                442
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     294
USA                        291
Hong Kong                  284
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

Task 69: Calculate the average transaction value for each country.

In [ ]:
data.groupby('Country')['Total_Price'].mean()

Country
Australia               108.910787
Austria                  25.322494
Bahrain                  28.863158
Belgium                  19.773301
Brazil                   35.737500
Canada                   24.280662
Channel Islands          26.520991
Cyprus                   21.045434
Czech Republic           23.590667
Denmark                  48.247147
European Community       21.176230
Finland                  32.124806
France                   23.102343
Germany                  23.365978
Greece                   32.263836
Hong Kong                34.888169
Iceland                  23.681319
Ireland                  32.135066
Israel                   26.877449
Italy                    21.034259
Japan                    98.716816
Lebanon                  37.641778
Lithuania                47.458857
Malta                    19.728110
Netherlands             120.059696
Norway                   32.378877
Poland                   21.152903
Portugal                 19.405940
RSA                      17.281207
Saudi Arabia             13.117000
Singapore                39.827031
Spain                    21.659822
Sweden                   79.360976
Switzerland              28.266324
UK                       16.657410
USA                       5.948179
United Arab Emirates     27.974706
Unspecified              10.726109
Name: Total_Price, dtype: float64

Task 70: Find which country has the highest average order value.

In [ ]:
data.groupby('Country')['Total_Price'].mean().sort_values(ascending=False).head(1)

Country
Netherlands    120.059696
Name: Total_Price, dtype: float64

Task 71: Calculate the total quantity of products sold to each country.

In [ ]:
data.groupby('Country')['Quantity'].sum()

Country
Australia                 83643
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9473
Cyprus                     6296
Czech Republic              592
Denmark                    8188
European Community          497
Finland                   10666
France                   110438
Germany                  117341
Greece                     1556
Hong Kong                  4709
Iceland                    2458
Ireland                  142495
Israel                     4350
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16153
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26817
Sweden                    35632
Switzerland               30313
UK                      4250328
USA                        1034
United Arab Emirates        982
Unspecified                3295
Name: Quantity, dtype: int64

Task 72: Find the country with the most unique customers.

In [ ]:
data.groupby('Country')['CustomerID'].nunique()

Country
Australia                  9
Austria                   11
Bahrain                    3
Belgium                   25
Brazil                     1
Canada                     4
Channel Islands            9
Cyprus                     8
Czech Republic             1
Denmark                    9
European Community         1
Finland                   12
France                    88
Germany                   95
Greece                     4
Hong Kong                  1
Iceland                    1
Ireland                    4
Israel                     5
Italy                     15
Japan                      8
Lebanon                    1
Lithuania                  1
Malta                      2
Netherlands                9
Norway                    10
Poland                     6
Portugal                  20
RSA                        1
Saudi Arabia               1
Singapore                  1
Spain                     31
Sweden                     8
Switzerland               22
UK                      3951
USA                        4
United Arab Emirates       2
Unspecified                5
Name: CustomerID, dtype: int64

#PART J: Time-based Analysis

Task 73: Calculate total revenue for each month.

In [ ]:
data.groupby('Month')['Total_Price'].sum()

Month
April         492367.841
August        681386.460
December     1179424.670
February      497026.410
January       558448.560
July          680156.991
June          689977.230
March         682013.980
May           722094.100
November     1456145.800
October      1069368.230
September    1017596.682
Name: Total_Price, dtype: float64

Task 74: Find which month had the highest sales.

In [ ]:
max_sales = data['Total_Price'].max()

In [ ]:
best_month = data[data['Total_Price'] == max_sales]['Month'].values

In [ ]:
best_month

array(['December'], dtype=object)

Task 75: Calculate revenue for each quarter.

In [ ]:
data.head(1)

InvoiceNo StockCode                         ProductName  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   

          InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0 2010-12-01 08:26:00       2.55       17850      UK         15.3  2010   

      Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  
0  December    1     8  Wednesday      Q4           Medium    Medium

In [ ]:
quarterly_revenue = data.groupby('Quarter')['Total_Price'].sum().reset_index()
quarterly_revenue

Quarter  Total_Price
0      Q1  1737488.950
1      Q2  1904439.171
2      Q3  2379140.133
3      Q4  3704938.700

Task 76: Calculate the number of transactions per day of the week.

In [ ]:
transactions_per_day = data['DayOfWeek'].value_counts().reset_index()

transactions_per_day.columns = ['DayOfWeek', 'TransactionCount']

transactions_per_day

DayOfWeek  TransactionCount
0   Thursday            103056
1    Tuesday            101064
2     Monday             94435
3  Wednesday             93715
4     Friday             81565
5     Sunday             62806

Task 77: Find which day of the week has the highest average revenue.

In [ ]:
avg_revenue = data.groupby('DayOfWeek')['Total_Price'].mean().reset_index()
best_day = avg_revenue.loc[avg_revenue['Total_Price'].idxmax()]
best_day

DayOfWeek       Thursday
Total_Price    20.461706
Name: 3, dtype: object

Task 78: Calculate hourly sales patterns (revenue by hour of day).

In [ ]:
hourly_revenue = data.groupby('Hour')['Total_Price'].sum()

In [ ]:
hourly_revenue

Hour
6        -497.350
7       31009.320
8      281723.020
9      766524.171
10    1327329.891
11    1146457.490
12    1357595.120
13    1172985.870
14    1091408.741
15    1186819.410
16     727666.670
17     434834.541
18     140365.040
19      45864.930
20      15920.090
Name: Total_Price, dtype: float64

Task 79: Compare sales between 2010 and 2011.

In [ ]:
sales_by_year = data.groupby('Year')['Total_Price'].sum().reset_index()
sales_by_year

Year  Total_Price
0  2010   746723.610
1  2011  8979283.344

Task 80: Calculate month-over-month revenue growth rate.

In [ ]:
data['Month Growth Rate'] = data['Total_Price'].pct_change()

data['Month Growth Rate (%)'] = data['Month Growth Rate'] * 100


In [ ]:
data['Month Growth Rate (%)'].fillna(0, inplace=True)

/tmp/ipython-input-619642019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Month Growth Rate (%)'].fillna(0, inplace=True)


In [ ]:
data['Month Growth Rate (%)']

0          0.000000
1         32.941176
2          8.161259
3         -7.545455
4          0.000000
            ...    
536636   -38.554217
536637    23.529412
536638    31.746032
536639     0.000000
536640   -10.542169
Name: Month Growth Rate (%), Length: 536641, dtype: float64

#PART K: Customer Analysis

Task 81: Calculate total spending for each customer.

In [ ]:
cus_spending = data.groupby('CustomerID')['Total_Price'].sum()

In [ ]:
cus_spending.columns = ['Total_Price']

In [ ]:
cus_spending

CustomerID
0        1447487.53
12346          0.00
12347       4310.00
12348       1797.24
12349       1757.55
            ...    
18280        180.60
18281         80.82
18282        176.60
18283       2045.53
18287       1837.28
Name: Total_Price, Length: 4373, dtype: float64

Task 82: Find the top 20 customers by total spending.

In [ ]:
cus_spending.head(20)

CustomerID
0        1447487.53
12346          0.00
12347       4310.00
12348       1797.24
12349       1757.55
12350        334.40
12352       1545.41
12353         89.00
12354       1079.40
12355        459.40
12356       2811.43
12357       6207.67
12358       1168.06
12359       6182.98
12360       2662.06
12361        189.90
12362       5154.58
12363        552.00
12364       1313.10
12365        320.69
Name: Total_Price, dtype: float64

Task 83: Calculate the number of transactions per customer.

In [ ]:
transactions_per_customer = data.groupby('CustomerID')['InvoiceNo'].count().reset_index()

transactions_per_customer.columns = ['CustomerID', 'Transaction_Count']

transactions_per_customer

CustomerID  Transaction_Count
0              0             135037
1          12346                  2
2          12347                182
3          12348                 31
4          12349                 73
...          ...                ...
4368       18280                 10
4369       18281                  7
4370       18282                 13
4371       18283                721
4372       18287                 70

[4373 rows x 2 columns]

Task 84: Find the average order value for each customer.

In [ ]:
Avg_order = data.groupby('CustomerID')['ProductName'].count().reset_index()

transactions_per_customer.columns = ['CustomerID', 'AverageOrder']

transactions_per_customer

CustomerID  AverageOrder
0              0        135037
1          12346             2
2          12347           182
3          12348            31
4          12349            73
...          ...           ...
4368       18280            10
4369       18281             7
4370       18282            13
4371       18283           721
4372       18287            70

[4373 rows x 2 columns]

Task 85: Identify customers who have made only one purchase.

In [ ]:
one_purchase_customers = data.groupby('CustomerID').filter(lambda x: x['InvoiceNo'].nunique() == 1)

one_purchase_customers

InvoiceNo StockCode                          ProductName  Quantity  \
155       536384     82484    WOOD BLACK BOARD ANT WHITE FINISH         3   
156       536384     84755  COLOUR GLASS T-LIGHT HOLDER HANGING        48   
157       536384     22464          HANGING METAL HEART LANTERN        12   
158       536384     21324         HANGING MEDINA LANTERN SMALL         6   
159       536384     22457       NATURAL SLATE HEART CHALKBOARD        12   
...          ...       ...                                  ...       ...   
536533    581578     22993         SET OF 4 PANTRY JELLY MOULDS        12   
536534    581578     22907     PACK OF 20 NAPKINS PANTRY DESIGN        12   
536535    581578     22908        PACK OF 20 NAPKINS RED APPLES        12   
536536    581578     23215     JINGLE BELL HEART ANTIQUE SILVER        12   
536537    581578     22736           RIBBON REEL MAKING SNOWMEN        10   

               InvoiceDate  UnitPrice  CustomerID  Country  Total_Price  Year  \
155    2010-12-01 09:53:00       6.45       18074       UK        19.35  2010   
156    2010-12-01 09:53:00       0.65       18074       UK        31.20  2010   
157    2010-12-01 09:53:00       1.65       18074       UK        19.80  2010   
158    2010-12-01 09:53:00       2.95       18074       UK        17.70  2010   
159    2010-12-01 09:53:00       2.95       18074       UK        35.40  2010   
...                    ...        ...         ...      ...          ...   ...   
536533 2011-12-09 12:16:00       1.25       12713  Germany        15.00  2011   
536534 2011-12-09 12:16:00       0.85       12713  Germany        10.20  2011   
536535 2011-12-09 12:16:00       0.85       12713  Germany        10.20  2011   
536536 2011-12-09 12:16:00       2.08       12713  Germany        24.96  2011   
536537 2011-12-09 12:16:00       1.65       12713  Germany        16.50  2011   

           Month  Day  Hour  DayOfWeek Quarter Revenue_Category OrderSize  \
155     December    1     9  Wednesday      Q4           Medium     Small   
156     December    1     9  Wednesday      Q4           Medium     Large   
157     December    1     9  Wednesday      Q4           Medium    Medium   
158     December    1     9  Wednesday      Q4           Medium    Medium   
159     December    1     9  Wednesday      Q4           Medium    Medium   
...          ...  ...   ...        ...     ...              ...       ...   
536533  December    9    12     Friday      Q4           Medium    Medium   
536534  December    9    12     Friday      Q4           Medium    Medium   
536535  December    9    12     Friday      Q4           Medium    Medium   
536536  December    9    12     Friday      Q4           Medium    Medium   
536537  December    9    12     Friday      Q4           Medium    Medium   

        Month Growth Rate  Month Growth Rate (%)  
155             -5.161290            -516.129032  
156              0.612403              61.240310  
157             -0.365385             -36.538462  
158             -0.106061             -10.606061  
159              1.000000             100.000000  
...                   ...                    ...  
536533          -0.663300             -66.329966  
536534          -0.320000             -32.000000  
536535           0.000000               0.000000  
536536           1.447059             144.705882  
536537          -0.338942             -33.894231  

[28246 rows x 19 columns]

Task 86: Find customers who spent more than £10,000 in total.

In [ ]:
data[data['Total_Price'] > 10000]

InvoiceNo  StockCode                     ProductName  Quantity  \
14757     537632  AMAZONFEE                      AMAZON FEE         1   
61006     541431      23166  MEDIUM CERAMIC TOP STORAGE JAR     74215   
220825    556444      22502  PICNIC BASKET WICKER 60 PIECES        60   
297645   A563185          B                 Adjust bad debt         1   
535160    581483      23843     PAPER CRAFT , LITTLE BIRDIE     80995   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
14757  2010-12-07 15:08:00   13541.33           0      UK     13541.33  2010   
61006  2011-01-18 10:01:00       1.04       12346      UK     77183.60  2011   
220825 2011-06-10 15:28:00     649.50       15098      UK     38970.00  2011   
297645 2011-08-12 14:50:00   11062.06           0      UK     11062.06  2011   
535160 2011-12-09 09:15:00       2.08       16446      UK    168469.60  2011   

           Month  Day  Hour DayOfWeek Quarter Revenue_Category OrderSize  \
14757   December    7    15   Tuesday      Q4             High     Small   
61006    January   18    10   Tuesday      Q1             High     Large   
220825      June   10    15    Friday      Q2             High     Large   
297645    August   12    14    Friday      Q3             High     Small   
535160  December    9     9    Friday      Q4             High     Large   

        Month Growth Rate  Month Growth Rate (%)  
14757           -2.000000            -200.000000  
61006          237.220988           23722.098765  
220825         540.250000           54025.000000  
297645        1083.515686          108351.568627  
535160        1650.662745          165066.274510

Task 87: Calculate the average number of days between purchases for each customer.

In [ ]:
data.pivot_table(index=['CustomerID','Day'], values='Total_Price', aggfunc='mean')

Total_Price
CustomerID Day             
0          1       9.734073
           2       8.374600
           3      13.001194
           4      12.529524
           5      -0.714826
...                     ...
18283      28      3.481034
           30      4.406200
18287      12     26.350526
           22     26.388966
           28     23.560000

[16497 rows x 1 columns]

#PART L: Product Analysis

Task 88: Find the top 20 products by revenue.

In [ ]:
data.groupby('ProductName')['Total_Price'].sum().reset_index().sort_values(by='Total_Price', ascending=False).head(20)

ProductName  Total_Price
1087                      DOTCOM POSTAGE    206245.48
2904            REGENCY CAKESTAND 3 TIER    164459.49
3908  WHITE HANGING HEART T-LIGHT HOLDER     99612.42
2461                       PARTY BUNTING     98243.88
1855             JUMBO BAG RED RETROSPOT     92175.79
2791                  RABBIT NIGHT LIGHT     66661.63
2741                             POSTAGE     66230.64
2430      PAPER CHAIN KIT 50'S CHRISTMAS     63715.24
234        ASSORTED COLOUR BIRD ORNAMENT     58792.42
762                        CHILLI LIGHTS     53746.66
3512                      SPOTTY BUNTING     42030.67
1853             JUMBO BAG PINK POLKADOT     41584.43
403             BLACK RECORD COVER FRAME     40578.21
2511      PICNIC BASKET WICKER 60 PIECES     39619.50
3183    SET OF 3 CAKE TINS PANTRY DESIGN     37378.79
1067       DOORMAT KEEP CALM AND COME IN     36532.39
1822            JAM MAKING SET WITH JARS     36069.34
3958   WOOD BLACK BOARD ANT WHITE FINISH     35795.97
2043             LUNCH BAG RED RETROSPOT     34717.66
2728                      POPCORN HOLDER     33959.26

Task 89: Find the top 20 products by quantity sold.

In [ ]:
data.groupby('ProductName')['Quantity'].sum().reset_index().sort_values(by='Quantity', ascending=False).head(20)

ProductName  Quantity
3999   WORLD WAR 2 GLIDERS ASSTD DESIGNS     53751
1855             JUMBO BAG RED RETROSPOT     47260
2728                      POPCORN HOLDER     36322
234        ASSORTED COLOUR BIRD ORNAMENT     36282
2386     PACK OF 72 RETROSPOT CAKE CASES     36016
3908  WHITE HANGING HEART T-LIGHT HOLDER     35298
2791                  RABBIT NIGHT LIGHT     30631
2150              MINI PAINT SET VINTAGE     26437
2352           PACK OF 12 LONDON TISSUES     26299
2384  PACK OF 60 PINK PAISLEY CAKE CASES     24719
3737     VICTORIAN GLASS HANGING T-LIGHT     23825
242            ASSORTED COLOURS SILK FAN     23082
576                   BROCADE RING PURSE     23017
2815               RED  HARMONICA IN BOX     21836
1853             JUMBO BAG PINK POLKADOT     20992
3456                SMALL POPCORN HOLDER     20105
2430      PAPER CHAIN KIT 50'S CHRISTMAS     18876
2043             LUNCH BAG RED RETROSPOT     18658
104          60 TEATIME FAIRY CAKE CASES     18015
2461                       PARTY BUNTING     18010

Task 90: Calculate the average price for each product.

In [ ]:
data.groupby('ProductName')['Total_Price'].mean()

ProductName
*Boombox Ipod Classic           16.980000
*USB Office Mirror Ball          8.470000
10 COLOUR SPACEBOY PEN          16.633792
12 COLOURED PARTY BALLOONS       8.296467
12 DAISY PEGS IN WOOD BOX        7.316296
                                  ...    
wrongly marked carton 22804      0.000000
wrongly marked. 23343 in box     0.000000
wrongly sold (22719) barcode     0.000000
wrongly sold as sets             0.000000
wrongly sold sets                0.000000
Name: Total_Price, Length: 4212, dtype: float64

Task 91: Find products that have been sold to more than 10 different countries.

In [ ]:
products_country_count = (data.groupby('ProductName')['Country'].nunique().reset_index())

products_10_plus = products_country_count[products_country_count['Country'] > 10]

products_10_plus


ProductName  Country
2                  10 COLOUR SPACEBOY PEN       13
9           12 PENCIL SMALL TUBE WOODLAND       12
10    12 PENCILS SMALL TUBE RED RETROSPOT       12
12              12 PENCILS TALL TUBE POSY       11
13     12 PENCILS TALL TUBE RED RETROSPOT       13
...                                   ...      ...
4035                    WRAP PAISLEY PARK       14
4038                      WRAP RED APPLES       14
4040               WRAP RED VINTAGE DOILY       12
4073            ZINC FOLKART SLEIGH BELLS       11
4082          ZINC METAL HEART DECORATION       11

[524 rows x 2 columns]

Task 92: Identify the most expensive and cheapest products.

In [ ]:
most_expensive = data.loc[data['UnitPrice'].idxmax(), ['ProductName','UnitPrice']]

cheapest = data.loc[data['UnitPrice'].idxmin(), ['ProductName', 'UnitPrice']]

In [ ]:
most_expensive

ProductName     Manual
UnitPrice      38970.0
Name: 220826, dtype: object

In [ ]:
cheapest

ProductName    Adjust bad debt
UnitPrice            -11062.06
Name: 297646, dtype: object

#PART M: Advanced Grouping

Task 93: Calculate total revenue by Country and Year.

In [ ]:
total_revenue = data.groupby(['Country', 'Year'])['Total_Price'].sum().reset_index()

In [ ]:
total_revenue

Country  Year  Total_Price
0              Australia  2010      937.600
1              Australia  2011   136072.170
2                Austria  2010      257.040
3                Austria  2011     9897.280
4                Bahrain  2010      205.740
..                   ...   ...          ...
56                    UK  2010   674615.860
57                    UK  2011  7492512.324
58                   USA  2011     1730.920
59  United Arab Emirates  2011     1902.280
60           Unspecified  2011     4740.940

[61 rows x 3 columns]

Task 94: Calculate average transaction value by Country and Quarter.

In [ ]:
transaction_value = data.groupby(['InvoiceNo', 'Country'])['Total_Price'].sum().reset_index()

In [ ]:
avg_trans_value = data.groupby(['Country', 'Quarter'])['Total_Price'].mean().reset_index()

In [ ]:
avg_trans_value

Country Quarter  Total_Price
0               Australia      Q1   124.086799
1               Australia      Q2   126.623560
2               Australia      Q3    75.440421
3               Australia      Q4   128.985078
4                 Austria      Q1    57.089231
..                    ...     ...          ...
121  United Arab Emirates      Q1    29.641333
122  United Arab Emirates      Q3    26.658947
123           Unspecified      Q2    18.563253
124           Unspecified      Q3     7.302092
125           Unspecified      Q4    18.221698

[126 rows x 3 columns]

Task 95: Find the number of transactions by Country and Month.

In [ ]:
transactions = (data.groupby(['Country', 'Year', 'Month'])['InvoiceNo'].nunique().reset_index(name='Transaction_Count'))

In [ ]:
transactions

Country  Year      Month  Transaction_Count
0      Australia  2010   December                  4
1      Australia  2011      April                  4
2      Australia  2011     August                  2
3      Australia  2011   February                  6
4      Australia  2011    January                  9
..           ...   ...        ...                ...
309  Unspecified  2011       July                  4
310  Unspecified  2011       June                  1
311  Unspecified  2011        May                  2
312  Unspecified  2011   November                  2
313  Unspecified  2011  September                  1

[314 rows x 4 columns]

Task 96: Calculate total revenue by Day of Week and Hour.

In [ ]:
summary = (data.groupby(['DayOfWeek', 'Hour'])['Total_Price'].sum().reset_index(name='Total_Revenue'))

In [ ]:
summary

DayOfWeek  Hour  Total_Revenue
0      Friday     7      17234.990
1      Friday     8      52535.930
2      Friday     9     155935.531
3      Friday    10     218800.930
4      Friday    11     204190.530
..        ...   ...            ...
70  Wednesday    16     124071.040
71  Wednesday    17      36946.580
72  Wednesday    18          0.000
73  Wednesday    19       2893.400
74  Wednesday    20      13031.500

[75 rows x 3 columns]

Task 97: For each country, calculate the sum, mean, maximum, and minimum TotalPrice.

In [ ]:
data.pivot_table(index='Country', values='Total_Price', aggfunc=['sum', 'mean', 'max', 'min'])

sum        mean         max         min
                      Total_Price Total_Price Total_Price Total_Price
Country                                                              
Australia              137009.770  108.910787     1718.40     -425.00
Austria                 10154.320   25.322494      360.00      -21.25
Bahrain                   548.400   28.863158      205.74     -205.74
Belgium                 40910.960   19.773301      165.00      -19.95
Brazil                   1143.600   35.737500      175.20       15.00
Canada                   3666.380   24.280662      550.94        2.50
Channel Islands         20076.390   26.520991      408.00     -293.00
Cyprus                  12858.760   21.045434      320.69     -320.69
Czech Republic            707.720   23.590667       70.80      -35.76
Denmark                 18768.140   48.247147      428.40      -59.80
European Community       1291.750   21.176230       60.00       -8.50
Finland                 22326.740   32.124806      551.20      -80.00
France                 197317.110   23.102343     4161.06    -8322.12
Germany                221509.470   23.365978      876.00     -599.50
Greece                   4710.520   32.263836      175.20      -50.00
Hong Kong                9908.240   34.888169     2653.95    -2653.95
Iceland                  4310.000   23.681319      249.60        5.04
Ireland                262993.380   32.135066     2365.20    -1917.00
Israel                   7901.970   26.877449      350.40     -136.00
Italy                   16890.510   21.034259      300.00      -89.55
Japan                   35340.620   98.716816     3794.40    -1591.20
Lebanon                  1693.880   37.641778      153.00       10.20
Lithuania                1661.060   47.458857      122.40       13.20
Malta                    2505.470   19.728110      455.00     -130.00
Netherlands            284661.540  120.059696     4992.00     -266.40
Norway                  35163.460   32.378877      700.00     -376.50
Poland                   7213.140   21.152903      120.00      -39.80
Portugal                29302.970   19.405940     1241.98    -1241.98
RSA                      1002.310   17.281207       38.25        0.00
Saudi Arabia              131.170   13.117000       19.80      -14.75
Singapore                9120.390   39.827031     3949.32    -3949.32
Spain                   54756.030   21.659822     1350.00    -1715.85
Sweden                  36585.410   79.360976     1188.00    -1188.00
Switzerland             56363.050   28.266324      360.00     -179.00
UK                    8167128.184   16.657410   168469.60  -168469.60
USA                      1730.920    5.948179       81.36      -74.88
United Arab Emirates     1902.280   27.974706      153.00        3.48
Unspecified              4740.940   10.726109       69.36        0.19

Task 98: For each customer, calculate their total spending, number of orders, and average order value.

In [ ]:
order_summary = (data.groupby(['CustomerID', 'InvoiceNo'])['Total_Price'].sum().reset_index())

In [ ]:
customer_summary = (order_summary.groupby('CustomerID').agg(Total_Spending=('Total_Price', 'sum'),Number_of_Orders=('InvoiceNo', 'nunique'),Avg_Order_Value=('Total_Price', 'mean')).reset_index())

In [ ]:
customer_summary

CustomerID  Total_Spending  Number_of_Orders  Avg_Order_Value
0              0      1447487.53              3710       390.158364
1          12346            0.00                 2         0.000000
2          12347         4310.00                 7       615.714286
3          12348         1797.24                 4       449.310000
4          12349         1757.55                 1      1757.550000
...          ...             ...               ...              ...
4368       18280          180.60                 1       180.600000
4369       18281           80.82                 1        80.820000
4370       18282          176.60                 3        58.866667
4371       18283         2045.53                16       127.845625
4372       18287         1837.28                 3       612.426667

[4373 rows x 4 columns]

Task 99: For each product, calculate total quantity sold and total revenue generated.

In [ ]:
data['Revenue'] = data['Quantity'] * data['UnitPrice']

In [ ]:
product_summary = (data.groupby('Total_Price').agg(Total_Quantity_Sold=('Quantity', 'sum'),Total_Revenue=('Revenue', 'sum')).reset_index())

In [ ]:
product_summary

Total_Price  Total_Quantity_Sold  Total_Revenue
0      -168469.60               -80995     -168469.60
1       -77183.60               -74215      -77183.60
2       -38970.00                   -1      -38970.00
3       -17836.46                   -1      -17836.46
4       -16888.02                   -1      -16888.02
...           ...                  ...            ...
6199     11062.06                    1       11062.06
6200     13541.33                    1       13541.33
6201     38970.00                   60       38970.00
6202     77183.60                74215       77183.60
6203    168469.60                80995      168469.60

[6204 rows x 3 columns]

#PART N: Creating Summary Reports

Task 100: Create a summary table showing monthly sales for each country (countries as rows, months as columns).

In [ ]:
summary_table = pd.pivot_table(data,values='Revenue',index='Country',columns='Month',aggfunc='sum',fill_value=0)

In [ ]:
summary_table

Month                      April     August    December   February    January  \
Country                                                                         
Australia                333.400   22489.20      937.60   14627.47    9017.71   
Austria                  680.780    1516.08      940.24     518.36       0.00   
Bahrain                    0.000       0.00      205.74       0.00    -205.74   
Belgium                 1954.150    3536.12     3219.34    2161.32    1154.05   
Brazil                  1143.600       0.00        0.00       0.00       0.00   
Canada                     0.000      51.56        0.00       0.00       0.00   
Channel Islands          293.000    4882.63      557.68    1784.71     645.08   
Cyprus                   -35.800       0.00     1495.82    4013.55     547.50   
Czech Republic           -57.510       0.00        0.00     549.26       0.00   
Denmark                    0.000      78.60     1450.40     399.22       0.00   
European Community       191.400       0.00        0.00       0.00       0.00   
Finland                 1626.810    1371.55     2123.48     205.16     889.02   
France                  4195.210   13789.26    16624.19    8438.91   17503.07   
Germany                11963.370   19023.65    22332.14    8969.24   16421.43   
Greece                   609.740       0.00      680.99       0.00    2661.24   
Hong Kong               1539.640    2813.95        0.00       0.00    2230.96   
Iceland                  636.250     584.91      936.61       0.00     475.39   
Ireland                 7570.500   12147.92    16352.99    9629.14   21656.52   
Israel                   110.000    4873.81     -227.44     779.10     379.84   
Italy                    737.830    1934.80      994.95     251.50    2361.36   
Japan                   4871.830     -49.79     7588.14    5780.81    -109.80   
Lebanon                    0.000       0.00        0.00       0.00    1693.88   
Lithuania                  0.000       0.00     1661.06       0.00       0.00   
Malta                      0.000    1103.25      -30.81       0.00       0.00   
Netherlands             2976.560   39655.81    20512.50   22932.11   26611.16   
Norway                     0.000    1984.46     6572.82     630.90       0.00   
Poland                   705.840     401.80      248.16     604.05     613.22   
Portugal                1687.750    1206.40     5182.07    1213.90    3998.11   
RSA                        0.000       0.00        0.00       0.00       0.00   
Saudi Arabia               0.000       0.00        0.00     145.92       0.00   
Singapore               2118.740       0.00        0.00       0.00    2053.07   
Spain                   1785.650    3325.91     2115.16    2093.70    7178.54   
Sweden                   809.100    1380.46     2646.30     509.50    3446.32   
Switzerland             1822.190    4882.19     1304.92    2642.67    4231.23   
UK                    441414.761  537870.90  1062384.34  407256.67  432995.40   
USA                      383.950       0.00      615.28       0.00       0.00   
United Arab Emirates       0.000       0.00        0.00     889.24       0.00   
Unspecified              299.100     531.03        0.00       0.00       0.00   

Month                       July       June      March        May    November  \
Country                                                                         
Australia               4767.570   25164.77   17055.29   13628.51     6805.99   
Austria                 1191.950     -24.20    1708.12    1249.43     1329.78   
Bahrain                    0.000       0.00       0.00     548.40        0.00   
Belgium                 2473.620    4273.17    3333.58    2727.00     6229.41   
Brazil                     0.000       0.00       0.00       0.00        0.00   
Canada                  1768.580    1171.46     140.54     534.24        0.00   
Channel Islands            0.000    2060.03    3509.33     903.79     1495.17   
Cyprus                     0.0

Task 101: Create a summary showing average quantity purchased by country and quarter.

In [ ]:
summary = (data.groupby(['Country', 'Quarter'])['Quantity'].mean().reset_index(name='Avg_Quantity'))

In [ ]:
summary

Country Quarter  Avg_Quantity
0               Australia      Q1     75.097561
1               Australia      Q2     81.433657
2               Australia      Q3     50.929907
3               Australia      Q4     62.435233
4                 Austria      Q1     33.948718
..                    ...     ...           ...
121  United Arab Emirates      Q1     16.533333
122  United Arab Emirates      Q3     12.789474
123           Unspecified      Q2     14.012048
124           Unspecified      Q3      4.872549
125           Unspecified      Q4     12.094340

[126 rows x 3 columns]

Task 102: Create a table showing the count of transactions in each RevenueCategory by Country.



In [ ]:
transaction_category = (data.groupby(['InvoiceNo', 'Country'])['Revenue_Category'].first().reset_index())

In [ ]:
summary_table = (transaction_category.groupby(['Country', 'Revenue_Category'])['InvoiceNo'].count().reset_index(name='Transaction_Count'))

/tmp/ipython-input-3622271516.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary_table = (transaction_category.groupby(['Country', 'Revenue_Category'])['InvoiceNo'].count().reset_index(name='Transaction_Count'))


In [ ]:
summary_table

Country Revenue_Category  Transaction_Count
0               Australia              Low                 13
1               Australia           Medium                 38
2               Australia             High                 18
3                 Austria              Low                  4
4                 Austria           Medium                 13
..                    ...              ...                ...
109  United Arab Emirates           Medium                  3
110  United Arab Emirates             High                  0
111           Unspecified              Low                  5
112           Unspecified           Medium                  8
113           Unspecified             High                  0

[114 rows x 3 columns]

#PART O: Data Transformation

Task 103: Add a column to each row showing what percentage of the monthly total revenue that transaction represents.

In [ ]:
monthly_revenue = (data.groupby(['Year', 'Month'])['Revenue'].transform('sum'))

In [ ]:
data['Monthly_Revenue_Percentage'] = (data['Revenue'] / monthly_revenue) * 100

In [ ]:
data[['InvoiceNo','Revenue','Monthly_Revenue_Percentage']].head(10)

InvoiceNo  Revenue  Monthly_Revenue_Percentage
0    536365    15.30                    0.002049
1    536365    20.34                    0.002724
2    536365    22.00                    0.002946
3    536365    20.34                    0.002724
4    536365    20.34                    0.002724
5    536365    15.30                    0.002049
6    536365    25.50                    0.003415
7    536366    11.10                    0.001486
8    536366    11.10                    0.001486
9    536367    54.08                    0.007242

Task 104: Add a column showing each customer's ranking based on their total spending.

In [ ]:
data['Total_Spending'] = data.groupby('CustomerID')['Total_Price'].sum()

In [ ]:
data['Total_Spending_Rank'] = data['Total_Spending'].rank(ascending=False)

In [ ]:
data[['CustomerID', 'Total_Spending', 'Total_Spending_Rank']].head(10)

CustomerID  Total_Spending  Total_Spending_Rank
0       17850      1447487.53                  1.0
1       17850             NaN                  NaN
2       17850             NaN                  NaN
3       17850             NaN                  NaN
4       17850             NaN                  NaN
5       17850             NaN                  NaN
6       17850             NaN                  NaN
7       17850             NaN                  NaN
8       17850             NaN                  NaN
9       13047             NaN                  NaN

Task 105: Add a column showing the cumulative revenue over time.

In [ ]:
data['Cumulative_Revenue'] = data.groupby('CustomerID')['Total_Price'].sum()

In [ ]:
data[['CustomerID', 'Total_Price', 'Cumulative_Revenue']].head(10)

CustomerID  Total_Price  Cumulative_Revenue
0       17850        15.30          1447487.53
1       17850        20.34                 NaN
2       17850        22.00                 NaN
3       17850        20.34                 NaN
4       17850        20.34                 NaN
5       17850        15.30                 NaN
6       17850        25.50                 NaN
7       17850        11.10                 NaN
8       17850        11.10                 NaN
9       13047        54.08                 NaN

#PART P: Combining Analysis

Task 106: Split the dataset into two parts: 2010 data and 2011 data. Then combine them back together vertically.

In [ ]:
data_2010 = data[data['Year'] == 2010]

In [ ]:
data_2011 = data[data['Year'] == 2011]

In [ ]:
data_combined = pd.concat([data_2010, data_2011])

In [ ]:
data_combined

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
536636    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
536637    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
536638    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
536639    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
536640    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK        15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK        22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK        20.34  2010   
...                    ...        ...         ...     ...          ...   ...   
536636 2011-12-09 12:50:00       0.85       12680  France        10.20  2011   
536637 2011-12-09 12:50:00       2.10       12680  France        12.60  2011   
536638 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536639 2011-12-09 12:50:00       4.15       12680  France        16.60  2011   
536640 2011-12-09 12:50:00       4.95       12680  France        14.85  2011   

        ... Quarter  Revenue_Category  OrderSize Month Growth Rate  \
0       ...      Q4            Medium     Medium               NaN   
1       ...      Q4            Medium     Medium          0.329412   
2       ...      Q4            Medium     Medium          0.081613   
3       ...      Q4            Medium     Medium         -0.075455   
4       ...      Q4            Medium     Medium          0.000000   
...     ...     ...               ...        ...               ...   
536636  ...      Q4            Medium     Medium         -0.385542   
536637  ...      Q4            Medium     Medium          0.235294   
536638  ...      Q4            Medium      Small          0.317460   
536639  ...      Q4            Medium      Small          0.000000   
536640  ...      Q4            Medium      Small         -0.105422   

       Month Growth Rate (%) Revenue Monthly_Revenue_Percentage  \
0                   0.000000   15.30                   0.002049   
1                  32.941176   20.34                   0.002724   
2                   8.161259   22.00                   0.002946   
3                  -7.545455   20.34                   0.002724   
4                   0.000000   20.34                   0.002724   
...                      ...     ...                        ...   
536636            -38.554217   10.20                   0.002357   
536637             23.529412   12.60                   0.002912   
536638             31.746032   16.60                   0.003836   
536639              0.000000   16.60                   0.003836   
536640            -10.542169   14.85                   0.003432   

        Total_Spending  Total_Spending_Rank  Cumulative_Revenue  
0           1447487.53                  1.0          1447487.53  
1                  NaN                  NaN                 NaN  
2                  NaN                  NaN                 NaN  
3                  NaN                  NaN                 NaN  
4                  NaN                  NaN                 NaN  
...                ...                  ...                 ...  
536636       

Task 107: Create separate datasets for UK and non-UK transactions. Combine them back horizontally with appropriate labeling.

In [ ]:
uk_data = data[data['Country'] == 'United Kingdom'].copy()
uk_data['Region'] = 'UK'

In [ ]:
non_uk_data = data[data['Country'] != 'United Kingdom'].copy()
non_uk_data['Region'] = 'Non-UK'

In [ ]:
combined = pd.concat([uk_data.reset_index(drop=True),non_uk_data.reset_index(drop=True)],axis=1)

In [ ]:
combined

InvoiceNo StockCode ProductName  Quantity InvoiceDate  UnitPrice  \
0            NaN       NaN         NaN       NaN         NaT        NaN   
1            NaN       NaN         NaN       NaN         NaT        NaN   
2            NaN       NaN         NaN       NaN         NaT        NaN   
3            NaN       NaN         NaN       NaN         NaT        NaN   
4            NaN       NaN         NaN       NaN         NaT        NaN   
...          ...       ...         ...       ...         ...        ...   
536636       NaN       NaN         NaN       NaN         NaT        NaN   
536637       NaN       NaN         NaN       NaN         NaT        NaN   
536638       NaN       NaN         NaN       NaN         NaT        NaN   
536639       NaN       NaN         NaN       NaN         NaT        NaN   
536640       NaN       NaN         NaN       NaN         NaT        NaN   

        CustomerID Country  Total_Price  Year  ... Revenue_Category  \
0              NaN     NaN          NaN   NaN  ...           Medium   
1              NaN     NaN          NaN   NaN  ...           Medium   
2              NaN     NaN          NaN   NaN  ...           Medium   
3              NaN     NaN          NaN   NaN  ...           Medium   
4              NaN     NaN          NaN   NaN  ...           Medium   
...            ...     ...          ...   ...  ...              ...   
536636         NaN     NaN          NaN   NaN  ...           Medium   
536637         NaN     NaN          NaN   NaN  ...           Medium   
536638         NaN     NaN          NaN   NaN  ...           Medium   
536639         NaN     NaN          NaN   NaN  ...           Medium   
536640         NaN     NaN          NaN   NaN  ...           Medium   

        OrderSize  Month Growth Rate Month Growth Rate (%) Revenue  \
0          Medium                NaN              0.000000   15.30   
1          Medium           0.329412             32.941176   20.34   
2          Medium           0.081613              8.161259   22.00   
3          Medium          -0.075455             -7.545455   20.34   
4          Medium           0.000000              0.000000   20.34   
...           ...                ...                   ...     ...   
536636     Medium          -0.385542            -38.554217   10.20   
536637     Medium           0.235294             23.529412   12.60   
536638      Small           0.317460             31.746032   16.60   
536639      Small           0.000000              0.000000   16.60   
536640      Small          -0.105422            -10.542169   14.85   

       Monthly_Revenue_Percentage Total_Spending  Total_Spending_Rank  \
0                        0.002049     1447487.53                  1.0   
1                        0.002724            NaN                  NaN   
2                        0.002946            NaN                  NaN   
3                        0.002724            NaN                  NaN   
4                        0.002724            NaN                  NaN   
...                           ...            ...                  ...   
536636                   0.002357            NaN                  NaN   
536637                   0.002912            NaN                  NaN   
536638                   0.003836            NaN                  NaN   
536639                   0.003836            NaN                  NaN   
536640                   0.003432            NaN                  NaN   

        Cumulative_Revenue  Region  
0               1447487.53  Non-UK  
1                      NaN  Non-UK  
2                      NaN  Non-UK  
3                      NaN  Non-UK  
4                      NaN  Non-UK  
...                    ...     ...  
536636                 NaN  Non-UK  
536637                 NaN  Non-UK  
536638                 NaN  Non-UK  
536639                 NaN  Non-UK  
536640                 NaN  Non-UK  

[536641 rows x 50 columns]

#PART Q: External Data Integration
Task 108: Create a new dataset with customer information (make up data):
* CustomerID, CustomerName, MembershipLevel (Bronze/Silver/Gold), JoinDate

In [ ]:
unique_customers = data['CustomerID'].dropna().unique()

names = ["Virat Kohali", "Rohit Sharma", "Ravindhra Jadeja", "Ravindhra Ashwin", "Suresh Raina",
         "M.S.Dhoni", "Ruthuraj Gaikward", "Shivam Dube", "Rachen Ravendhra", "Pathirana"]

levels = ["Bronze", "Silver", "Gold"]

customer_info = pd.DataFrame({
    'CustomerID': unique_customers[:10],
    'CustomerName': names,
    'MembershipLevel': np.random.choice(levels, size=10),
    'JoinDate': pd.date_range(start="2020-01-01", periods=10, freq='180D')
})

customer_info

CustomerID       CustomerName MembershipLevel   JoinDate
0       17850       Virat Kohali          Silver 2020-01-01
1       13047       Rohit Sharma            Gold 2020-06-29
2       12583   Ravindhra Jadeja          Silver 2020-12-26
3       13748   Ravindhra Ashwin          Silver 2021-06-24
4       15100       Suresh Raina            Gold 2021-12-21
5       15291          M.S.Dhoni          Silver 2022-06-19
6       14688  Ruthuraj Gaikward            Gold 2022-12-16
7       17809        Shivam Dube          Bronze 2023-06-14
8       15311   Rachen Ravendhra            Gold 2023-12-11
9       14527          Pathirana          Bronze 2024-06-08

Task 109: Combine this customer dataset with your sales data to show customer names and membership levels in transactions.

In [ ]:
merged_data = data.merge(customer_info, on='CustomerID', how='left')

In [ ]:
merged_data[['InvoiceNo', 'CustomerID', 'CustomerName', 'MembershipLevel']].head(10)

InvoiceNo  CustomerID  CustomerName MembershipLevel
0    536365       17850  Virat Kohali          Silver
1    536365       17850  Virat Kohali          Silver
2    536365       17850  Virat Kohali          Silver
3    536365       17850  Virat Kohali          Silver
4    536365       17850  Virat Kohali          Silver
5    536365       17850  Virat Kohali          Silver
6    536365       17850  Virat Kohali          Silver
7    536366       17850  Virat Kohali          Silver
8    536366       17850  Virat Kohali          Silver
9    536367       13047  Rohit Sharma            Gold

Task 110: Create a product categories dataset (make up data):

StockCode, Category (e.g., Home, Kitchen, Gift, etc.)

In [ ]:
unique_codes = data['StockCode'].dropna().unique()

categories = ["Home", "Kitchen", "Gift", "Toys", "Decor", "Stationery"]

product_categories = pd.DataFrame({
    'StockCode': unique_codes[:20],  # assign categories to first 20 codes
    'Category': np.random.choice(categories, size=20)
})

product_categories

StockCode    Category
0     85123A        Toys
1      71053        Home
2     84406B        Gift
3     84029G       Decor
4     84029E        Toys
5      22752        Toys
6      21730       Decor
7      22633        Toys
8      22632  Stationery
9      84879        Gift
10     22745  Stationery
11     22748       Decor
12     22749        Home
13     22310       Decor
14     84969        Toys
15     22623     Kitchen
16     22622     Kitchen
17     21754        Toys
18     21755        Home
19     21777        Home

Task 111: Combine the sales data with product categories to analyze which categories generate the most revenue.

In [ ]:
merged_sales = data.merge(product_categories, on='StockCode', how='left')

In [ ]:
category_revenue = (merged_sales.groupby('Category')['Revenue'].sum().reset_index().sort_values('Revenue', ascending=False))

In [ ]:
category_revenue

Category    Revenue
5        Toys  162238.71
1        Gift   66283.09
2        Home   29963.42
0       Decor   24677.23
3     Kitchen   18931.07
4  Stationery   13558.17

Task 112: Perform an analysis that shows total revenue by MembershipLevel.

In [ ]:
revenue = merged_data.groupby('MembershipLevel')['Revenue'].sum().reset_index()

In [ ]:
revenue

MembershipLevel   Revenue
0          Bronze  12337.31
1            Gold  68054.00
2          Silver  18035.58

Task 113: Show which product categories are most popular in each country.

In [ ]:
data.columns

Index(['InvoiceNo', 'StockCode', 'ProductName', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Total_Price', 'Year', 'Month',
       'Day', 'Hour', 'DayOfWeek', 'Quarter', 'Revenue_Category', 'OrderSize',
       'Month Growth Rate', 'Month Growth Rate (%)', 'Revenue',
       'Monthly_Revenue_Percentage', 'Total_Spending', 'Total_Spending_Rank',
       'Cumulative_Revenue'],
      dtype='object')

In [ ]:
category_popularity = (data.groupby(['Country', 'Revenue_Category'])['Quantity'].sum().reset_index())

/tmp/ipython-input-3121191971.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  category_popularity = (data.groupby(['Country', 'Revenue_Category'])['Quantity'].sum().reset_index())


In [ ]:
most_popular_by_country = (category_popularity.loc[category_popularity.groupby('Country')['Quantity'].idxmax()])

In [ ]:
most_popular_by_country

Country Revenue_Category  Quantity
2               Australia             High     59553
4                 Austria           Medium      3715
7                 Bahrain           Medium       164
10                Belgium           Medium     20227
13                 Brazil           Medium       340
16                 Canada           Medium      1939
19        Channel Islands           Medium      7356
22                 Cyprus           Medium      5378
25         Czech Republic           Medium       671
28                Denmark           Medium      5102
31     European Community           Medium       487
34                Finland           Medium      8083
37                 France           Medium     87155
40                Germany           Medium     92612
43                 Greece           Medium      1170
46              Hong Kong           Medium      4091
49                Iceland           Medium      1954
52                Ireland           Medium     84845
55                 Israel           Medium      3381
58                  Italy           Medium      7399
62                  Japan             High     19428
64                Lebanon           Medium       358
67              Lithuania           Medium       604
70                  Malta           Medium       815
74            Netherlands             High    148870
76                 Norway           Medium     16707
79                 Poland           Medium      3300
82               Portugal           Medium     14118
85                    RSA           Medium       321
88           Saudi Arabia           Medium        68
91              Singapore           Medium      4430
94                  Spain           Medium     19174
98                 Sweden             High     28074
100           Switzerland           Medium     23462
103                    UK           Medium   2493861
106                   USA           Medium      2275
109  United Arab Emirates           Medium       882
112           Unspecified           Medium      2637

#PART R: NumPy Operations

Task 114: Extract Quantity and UnitPrice as arrays and perform element-wise multiplication.

In [ ]:
element_wise = data['Quantity'] * data['UnitPrice']

In [ ]:
element_wise

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...  
536636    10.20
536637    12.60
536638    16.60
536639    16.60
536640    14.85
Length: 536641, dtype: float64

Task 115: Create an array of 1000 random transaction IDs.

In [ ]:
transaction_ids = np.random.randint(1000, size=1000)

In [ ]:
transaction_ids

array([ 81, 392, 372, 648, 502, 949, 643, 925, 147, 997, 363, 701, 974,
       829, 942, 481,  87, 327, 509, 578, 693, 178, 754, 221, 338, 923,
       842, 183,  23, 207, 470, 977, 252, 691, 425, 240, 698, 663, 918,
       981, 767, 920, 479, 744, 662, 236, 447, 910, 816, 402, 315, 346,
       520, 768, 359, 971, 947, 670, 354, 596, 834, 499, 318, 513, 792,
        21, 605, 692, 100, 651, 296, 269, 814, 337, 156, 759, 578, 901,
       668, 968, 866, 116, 268, 243, 676, 214, 160, 930, 695, 284, 484,
       485, 197, 425, 794, 699, 493, 131, 284, 854, 213, 898, 406, 633,
       986,   4, 325, 903, 479, 565,  95, 680, 818, 675,  90, 646, 273,
       265, 321,  66, 530, 912, 796,  80, 763, 686, 783, 907, 529, 153,
       855, 444, 232, 817, 120, 456, 500, 692, 706, 653,  92,  59, 849,
       216,  12, 750, 433, 746, 859, 139, 485, 479, 623, 478, 913, 167,
       422, 115,  40, 391, 558, 493, 719, 428,  76, 249, 975, 118,  72,
       466,  62, 921, 630, 377, 677, 137, 977, 442, 485,  65, 66

Task 116: Generate 50 equally spaced price points between £0 and £500.

In [ ]:
spaced_prices = np.linspace(0, 500, 50)

In [ ]:
spaced_prices

array([  0.        ,  10.20408163,  20.40816327,  30.6122449 ,
        40.81632653,  51.02040816,  61.2244898 ,  71.42857143,
        81.63265306,  91.83673469, 102.04081633, 112.24489796,
       122.44897959, 132.65306122, 142.85714286, 153.06122449,
       163.26530612, 173.46938776, 183.67346939, 193.87755102,
       204.08163265, 214.28571429, 224.48979592, 234.69387755,
       244.89795918, 255.10204082, 265.30612245, 275.51020408,
       285.71428571, 295.91836735, 306.12244898, 316.32653061,
       326.53061224, 336.73469388, 346.93877551, 357.14285714,
       367.34693878, 377.55102041, 387.75510204, 397.95918367,
       408.16326531, 418.36734694, 428.57142857, 438.7755102 ,
       448.97959184, 459.18367347, 469.3877551 , 479.59183673,
       489.79591837, 500.        ])

Task 117: Create a matrix representing 12 months and 7 product categories filled with zeros.

In [ ]:
matrix = np.zeros((12, 7), dtype = int)

In [ ]:
matrix

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

Task 118: Extract quantities greater than 100 from the Quantity array.

In [ ]:
quantities = data[data['Quantity'] > 100]

In [ ]:
quantities

InvoiceNo StockCode                        ProductName  Quantity  \
96        536378     21212    PACK OF 72 RETROSPOT CAKE CASES       120   
178       536387     79321                      CHILLI LIGHTS       192   
179       536387     22780     LIGHT GARLAND BUTTERFILES PINK       192   
180       536387     22779          WOODEN OWLS LIGHT GARLAND       192   
181       536387     22466      FAIRY TALE COTTAGE NIGHTLIGHT       432   
...          ...       ...                                ...       ...   
535181    581487     21137           BLACK RECORD COVER FRAME       120   
536025    581497     22355          CHARLOTTE BAG SUKI DESIGN       110   
536284    581501     22319  HAIRCLIPS FORTIES FABRIC ASSORTED       180   
536434    581566     23404         HOME SWEET HOME BLACKBOARD       144   
536443    581567     21326   AGED GLASS SILVER T-LIGHT HOLDER       144   

               InvoiceDate  UnitPrice  CustomerID Country  Total_Price  Year  \
96     2010-12-01 09:37:00       0.42       14688      UK        50.40  2010   
178    2010-12-01 09:58:00       3.82       16029      UK       733.44  2010   
179    2010-12-01 09:58:00       3.37       16029      UK       647.04  2010   
180    2010-12-01 09:58:00       3.37       16029      UK       647.04  2010   
181    2010-12-01 09:58:00       1.45       16029      UK       626.40  2010   
...                    ...        ...         ...     ...          ...   ...   
535181 2011-12-09 09:44:00       3.39       15694      UK       406.80  2011   
536025 2011-12-09 10:23:00       2.46           0      UK       270.60  2011   
536284 2011-12-09 10:46:00       0.19       12985      UK        34.20  2011   
536434 2011-12-09 11:50:00       3.26       18102      UK       469.44  2011   
536443 2011-12-09 11:56:00       0.55       16626      UK        79.20  2011   

        ... Quarter  Revenue_Category  OrderSize Month Growth Rate  \
96      ...      Q4            Medium      Large          2.294118   
178     ...      Q4              High      Large          3.445091   
179     ...      Q4              High      Large         -0.117801   
180     ...      Q4              High      Large          0.000000   
181     ...      Q4              High      Large         -0.031899   
...     ...     ...               ...        ...               ...   
535181  ...      Q4              High      Large         12.696970   
536025  ...      Q4              High      Large          0.617647   
536284  ...      Q4            Medium      Large          1.072727   
536434  ...      Q4              High      Large        374.552000   
536443  ...      Q4            Medium      Large          3.000000   

       Month Growth Rate (%) Revenue Monthly_Revenue_Percentage  \
96                229.411765   50.40                   0.006749   
178               344.509091  733.44                   0.098221   
179               -11.780105  647.04                   0.086651   
180                 0.000000  647.04                   0.086651   
181                -3.189911  626.40                   0.083886   
...                      ...     ...                        ...   
535181           1269.696970  406.80                   0.094014   
536025             61.764706  270.60                   0.062537   
536284            107.272727   34.20                   0.007904   
536434          37455.200000  469.44                   0.108491   
536443            300.000000   79.20                   0.018304   

        Total_Spending  Total_Spending_Rank  Cumulative_Revenue  
96                 NaN                  NaN                 NaN  
178                NaN                  NaN                 NaN  
179                NaN                  NaN                 NaN  
180                NaN                  NaN                 NaN  
181                NaN                  NaN                 NaN  
...                ...                  ...                 ...  
535181             NaN               

Task 119: Calculate the square root of all UnitPrice values.

In [ ]:
unitprice = np.sqrt(data['UnitPrice'])

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [ ]:
unitprice

0         1.596872
1         1.841195
2         1.658312
3         1.841195
4         1.841195
            ...   
536636    0.921954
536637    1.449138
536638    2.037155
536639    2.037155
536640    2.224860
Name: UnitPrice, Length: 536641, dtype: float64

Task 120: Find the 25th, 50th, and 75th percentiles of TotalPrice.

In [ ]:
total_price = data['Total_Price'].describe()

In [ ]:
total_price

count    536641.000000
mean         18.123861
std         380.656263
min     -168469.600000
25%           3.750000
50%           9.870000
75%          17.400000
max      168469.600000
Name: Total_Price, dtype: float64

Task 121: Round all UnitPrice values to the nearest integer.

In [ ]:
data['UnitPrice'].round().astype(int)

0         3
1         3
2         3
3         3
4         3
         ..
536636    1
536637    2
536638    4
536639    4
536640    5
Name: UnitPrice, Length: 536641, dtype: int64

Task 122: Find positions where Quantity is maximum.

In [ ]:
data['Quantity'].max()

80995

Task 123: Calculate the correlation between Quantity and UnitPrice.

In [ ]:
correlation = data['Quantity'].corr(data['UnitPrice'])

In [ ]:
correlation

np.float64(-0.001241039673356979)

Task 124: Normalize the TotalPrice column (subtract mean, divide by standard deviation).

In [ ]:
data['Normalized_TotalPrice'] = (data['Total_Price'] - data['Total_Price'].mean()) / data['Total_Price'].std()

In [ ]:
data['Normalized_TotalPrice']

0        -0.007418
1         0.005822
2         0.010183
3         0.005822
4         0.005822
            ...   
536636   -0.020816
536637   -0.014511
536638   -0.004003
536639   -0.004003
536640   -0.008601
Name: Normalized_TotalPrice, Length: 536641, dtype: float64

Task 125: Split the Quantity array into 4 equal parts.

In [ ]:
qty = data['Quantity'].values

parts = np.array_split(qty, 4)

for i, p in enumerate(parts):
    print(f"Part {i+1}:", p)

Part 1: [6 6 8 ... 2 1 4]
Part 2: [ 1  1  3 ... 25 25 25]
Part 3: [25 12 12 ...  1  1  4]
Part 4: [1 1 1 ... 4 4 3]


#PART S: Export and Documentation

Task 126: Save your cleaned dataset to a CSV file.

In [ ]:
data.to_csv('Blinked_dataset.csv', index=False)

Task 127: Save your cleaned dataset to an Excel file.

In [ ]:
data.to_excel("cleaned_dataset.xlsx", index=False)

Task 128: Create an Excel file with multiple sheets:

Sheet 1: Full cleaned data

Sheet 2: Country-wise summary

Sheet 3: Monthly revenue trends

Sheet 4: Top 50 customers

In [ ]:
data['Sales'] = data['Quantity'] * data['UnitPrice']

In [ ]:
# Sheet 1: Full cleaned data
sheet1 = data

In [ ]:
# Sheet 2: Country-wise summary
sheet2 = data.groupby('Country').agg({
    'Sales': 'sum',
    'Quantity': 'sum'
}).reset_index()

In [ ]:
# Sheet 3: Monthly revenue trends
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])
sheet3 = data.groupby(data['InvoiceDate'].dt.to_period('M'))['Sales'].sum().reset_index()
sheet3['InvoiceDate'] = sheet3['InvoiceDate'].astype(str)

In [ ]:
# Sheet 4: Top 50 customers
sheet4 = (
    data.groupby('CustomerID')['Sales']
    .sum()
    .reset_index()
    .sort_values(by='Sales', ascending=False)
    .head(50)
)

In [ ]:
!pip install xlsxwriter
# Create Excel with multiple sheets
with pd.ExcelWriter("analysis_report.xlsx", engine='xlsxwriter') as writer:

    # Sheet 1
    sheet1.to_excel(writer, sheet_name="Full Data", index=False)

    # Sheet 2
    sheet2.to_excel(writer, sheet_name="Country Summary", index=False)

    # Sheet 3
    sheet3.to_excel(writer, sheet_name="Monthly Revenue", index=False)

    # Sheet 4
    sheet4.to_excel(writer, sheet_name="Top 50 Customers", index=False)

print("Excel file created successfully!")


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 11.0 MB/s eta 0:00:00
Excel file created successfully!


Task 129: Export the pivot table from Task 100 to Excel.

In [ ]:
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])

pivot_100 = data.pivot_table(
    index='Country',
    columns=data['InvoiceDate'].dt.month,
    values='Sales',
    aggfunc='sum'
)

pivot_100.to_excel("pivot_task_100.xlsx", index=True)


Task 130: Create a text file documenting all the insights you discovered from this analysis.

In [ ]:
text = """
# Analysis Insights Summary

## 1. Sales Insights
- Identified highest sales months and seasonal patterns.
- Determined top-selling products based on revenue.
- Found that certain Outlet Establishment Years outperform others in total sales.

## 2. Customer Insights
- Identified top 50 customers based on total revenue generated.
- Customers with more frequent purchases tend to have higher lifetime value.
- Calculated average days between purchases for each customer.

## 3. Product Insights
- Determined top 20 products by revenue.
- Found products sold in more than 10 different countries.
- Identified most expensive and cheapest products.

## 4. Country-Level Insights
- Calculated total revenue by country.
- Countries with highest average order values identified.
- Monthly sales trends visualized for each country.

## 5. Time-Series Trends
- Monthly revenue trends show clear growth patterns.
- Specific months show peak demand depending on regions.

## 6. Data Cleaning Insights
- Missing CustomerID rows removed.
- Negative or zero Quantity values were cleaned.
- Missing descriptions filled with 'Unknown Product'.

## 7. NumPy Calculations
- Performed element-wise operations using Quantity and UnitPrice.
- Computed square roots, splits, and array transformations for deeper analysis.

## 8. Pivot Table Insights
- Monthly sales by country provided comparative performance views.
- Pivot exported for further reporting.

This document summarizes the key findings and analysis results obtained during the entire project.
"""

# --- Save to a text file using standard file handling ---
with open("analysis_insights.txt", "w", encoding="utf-8") as file:
    file.write(text)

print("File saved successfully!")


File saved successfully!


In [ ]:
file

<_io.TextIOWrapper name='analysis_insights.txt' mode='w' encoding='utf-8'>